AWS/legos/aws_list_access_keys/aws_list_access_keys.json

Json Syntax fix
aws_list_access_keys.json had a missing `}` at the end. Fixed it.

Json Syntax Fix

---

SSH/legos/ssh_execute_remote_command/ssh_execute_remote_command.py

Improve overriding proxy host.
```
(connectors) amits-mbp-2:unskript amit$ pytest -s tests/ssh/test_ssh_execute_command.py::test_ssh_execute_command_via_override_proxy
==================================================================================================================== test session starts =====================================================================================================================
tests/ssh/test_ssh_execute_command.py
{'10.0.1.169': 'fluent-bit\n'
'\n'
'jeg\n'
'\n'
'k3supgrade.yaml\n'
'\n'
'log.txt\n'
'\n'
'redis\n'
'\n'
'sidecar\n'
'\n'
'snap\n'
'\n' …
```

Make proxy_host to the handler itself

---

.github/workflows/build-and-release-docker.yml

Restricting Python version to 3.76 for the Docker builder.

Restricting Python version to 3.7.6

---

.github/workflows/build-and-release-docker.yml

The Github Workflow had a bug that `latest` tag was added for every build. Fixed the logic and tested it with two seperate builds. 
- [x ] My changes generate no new warnings.
- [] Any dependent changes have been merged and published. 
No changes needed

Removed required field and adding if condition to add tag only when true

---

AWS/legos/aws_list_expiring_access_keys/aws_list_expiring_access_keys.json
AWS/legos/aws_list_expiring_acm_certificates/aws_list_expiring_acm_certificates.json

We need to add following keys for health checkup support
- action_is_check =T or F
- action_categories
- action_next_hop
- action_next_hop_parameter_mapping
- action_output_type is always ACTION_OUTPUT_TYPE_LIST in case of a check

EN-3698 : Schema Changes supported for HealthCheck Epic

---

AWS/legos/aws_filter_unencrypted_s3_buckets/aws_filter_unencrypted_s3_buckets.json
AWS/legos/aws_filter_unencrypted_s3_buckets/aws_filter_unencrypted_s3_buckets.py

Check Lego Filter AWS Unencrypted S3 Buckets

EN-3791 - Check Lego Filter AWS Unencrypted S3 Buckets

---

Kafka/legos/kafka_run_command/kafka_run_command.py

Fix the kafka run command lego, also its printer function
```
(connectors) Amits-MacBook-Pro-2:unskript amit$ pytest -s tests/kafka/test_kafka_run_command.py
=================================================================================================================== test session starts ====================================================================================================================
collected 2 items
tests/kafka/test_kafka_run_command.py __consumer_offsets
dummy
log
my-topic
test
test_msg
wikipedia.recentchange
.__consumer_offsets
dummy
log
my-topic
test
test_msg
wikipedia.recentchange
```

EN-3890-test-out-kafka-legos

---

AWS/Terminate_EC2_Instances_Without_Valid_Lifetime_Tag.ipynb

Added Check lego to get instances without Termination and Lifetime Tag
https://user-images.githubusercontent.com/110628398/215515693-d314aa72-afc4-4fba-bfd9-1d2e8db382ac.mov

Runbook: Terminate EC2 instances without valid Lifetime Tag

---

Postgresql/legos/postgresql_read_query/postgresql_read_query.py

When adding addtional params to the "Read PostgreSQL Query" lego, it fails with the following error:

EN-3931: Fixed PostGres issue

---

AWS/Restrict_S3_Buckets_with_READ_WRITE_Permissions.ipynb

Added check lego and changed descriptions. 
Reference- Relay
https://user-images.githubusercontent.com/110628398/216388667-fe3978bb-2866-44e9-b053-605a7932eadf.mov

Runbook: Restrict S3 Buckets with read/write permissions

---

Postgresql/legos/postgresql_long_running_queries/README.md
Postgresql/legos/postgresql_long_running_queries/postgresql_long_running_queries.json
Postgresql/legos/postgresql_long_running_queries/postgresql_long_running_queries.py

1. Long Running PostgreSQL Queries

more_check_actions

---

AWS/Get_Aws_Elb_Unhealthy_Instances.ipynb
AWS/legos/aws_get_unhealthy_instances_from_elb/aws_get_unhealthy_instances_from_elb.json
AWS/legos/aws_get_unhealthy_instances_from_elb/aws_get_unhealthy_instances_from_elb.py

Get unhealthy EC2 instances from ELB

EN-3815 Runbook: Get unhealthy EC2 instances from ELB

---

Kubernetes/K8S_Get_Candidate_Nodes_Given_Config.ipynb

1. k8s: Get candidate nodes for the given configuration
https://user-images.githubusercontent.com/63058785/218448347-f38561d5-da05-4b72-b57b-98f0c609c69b.mp4

EN-3841 Runbook: k8s: Get candidate nodes for given configuration

---

Postgresql/Display_Postgresql_Long_Running.ipynb

Display Postgresql Long Running Queries
https://user-images.githubusercontent.com/63058785/218130606-a121c74e-ab0e-410b-8834-54dc5ea460b3.mp4

EN-3843 Runbook: Display Postgresql Long Running Queries

---

AWS/Lowering_AWS_CloudTrail_Costs_by_Removing_Redundant_Trails.ipynb
AWS/legos/aws_finding_redundant_trails/aws_finding_redundant_trails.py

Lowering AWS CloudTrail Costs by Removing Redundant Trails
https://user-images.githubusercontent.com/63058785/220335528-449235dc-dcb4-4da8-9984-7fa996938ef9.mp4

EN-3835 Runbook: Lowering AWS CloudTrail Costs by Removing Redundant Trails

---

SSH/legos/ssh_find_large_files/ssh_find_large_files.py
SSH/legos/ssh_restart_service_using_sysctl/ssh_restart_service_using_sysctl.py
SSH/legos/ssh_scp/ssh_scp.py

Fix all ssh legos to support proxy_host as optional field too
```
(connectors) Amits-MacBook-Pro-2:unskript amit$ pytest -s tests/ssh/test_ssh_scp.py
==================================================================================================== test session starts =====================================================================================================
tests/ssh/test_ssh_scp.py Execution Summary:
Number of Execution(s): 2
Iterator values:
{'remote': '/home/ec2-user/.ssh/authorized_keys', 'local': '/tmp/authorized_keys_10'}		: ✓
{'remote': '/home/ec2-user/.ssh/id_rsa', 'local': …
```

Fix the 2 other ssh legos

---

Jira/legos/jira_add_comment/README.md
Jira/legos/jira_add_comment/jira_add_comment.json
Jira/legos/jira_add_comment/jira_add_comment.py

Lego to add Jira comment
Add Jira comment
```
============================================================ test session starts ============================================================
platform linux -- Python 3.7.13, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/sagar/Unskript/unskript, configfile: setup.cfg
plugins: typeguard-2.13.3, anyio-3.5.0, cov-3.0.0
collected 1 item                                                                                                                            
test_jira_add_comment.py 11702
.
```
Add restricted jira comment
```
============================================================ test session starts ============================================================
platform linux -- Python 3.7.13, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 …
```

EN-4286: Jira add comment lego

---

.gitignore
README_extending_docker.md
README_template.md
custom/README.md
unskript-ctl/unskript-client.py

[EN-4270]
* Updates to README_template.md
* Updates to README_extending_docker.md
* Updates to unskript-ctl to reference  unskript-ctl instead of unskript-client
[EN-4270]: https://unskript.atlassian.net/browse/EN-4270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update to README

---

README_template.md

docs updates

---

Kafka/legos/kafka_check_in_sync_replicas/README.md
Kafka/legos/kafka_check_in_sync_replicas/kafka_check_in_sync_replicas.json
Kafka/legos/kafka_check_in_sync_replicas/kafka_check_in_sync_replicas.py
Kafka/legos/kafka_check_offline_partitions/README.md
Kafka/legos/kafka_check_offline_partitions/kafka_check_offline_partitions.json
Kafka/legos/kafka_check_offline_partitions/kafka_check_offline_partitions.py
Kafka/legos/kafka_check_replicas_available/README.md
Kafka/legos/kafka_check_replicas_available/kafka_check_replicas_available.json
Kafka/legos/kafka_check_replicas_available/kafka_check_replicas_available.py

Created legos:
kafka_check_in_sync_replicas
kafka_check_offline_partitions
kafka_check_replicas_available
[EN-4034]: https://unskript.atlassian.net/browse/EN-4034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EN-4034: Kafka Health Check Legos

---

Jira/legos/jira_create_issue/jira_create_issue.py

[EN-4338]
Create issue didnt create the labels. The issue was labels is an array of strings, unlike other fields. So need to special handling for that.
Also, raise an exception if a field is not found on the JIRA side.
Use a different way to get the username to accountId mapping.
```
connectors) amits-mbp-2:unskript amit$ pytest -s tests/jira/test_jira_create_issue.py::test_jira_create_issue_invalid_field
=================================================================================================================== test session starts ==================================================================================================================== …
```

En 4338 support for custom issue type and fix labels field

---

AWS/legos/aws_filter_untagged_ec2_instances/aws_filter_untagged_ec2_instances.py
infra/legos/infra_execute_runbook/infra_execute_runbook.py

Make params default value as None for the execute runbook lego.
Fix the untagged ec2 lego logic.
Make the params parameter to the execute runbook lego optional.
```
(connectors) amits-mbp-2:unskript amit$ pytest -s tests/aws/test_aws_filter_untagged_ec2_instances.py
=================================================================================================================== test session starts ====================================================================================================================
tests/aws/test_aws_filter_untagged_ec2_instances.py (False,
[{'instanceID': …
```

Fix the untagged ec2 logic

---

AWS/legos/aws_update_ttl_for_route53_records/README.md
AWS/legos/aws_update_ttl_for_route53_records/aws_update_ttl_for_route53_records.json
AWS/legos/aws_update_ttl_for_route53_records/aws_update_ttl_for_route53_records.py

[Issue-416](https://github.com/unskript/Awesome-CloudOps-Automation/issues/416)
I don't have permissions to change the TTL:

Action: AWS Change TTL for Route53 record

---

infra/legos/infra_execute_runbook/infra_execute_runbook.py

The infra execute runbook lego needs to take dict as input instead of json string of the params.
```
(connectors) Amits-MacBook-Pro-2:unskript amit$ pytest -s tests/infra/test_execute_runbook.py
==================================================================================================================== test session starts =====================================================================================================================
tests/infra/test_execute_runbook.py None
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> …
```

Param from string to dict

---

unskript-ctl/unskript-client.py

Fixes [EN-4306]
Adding support for `unskript-ctl` to run runbook that has parameters defined in them. 
This PR supports both `interactive` and `non-interactive` Runs. 
```
(base) root@ca93f4db0bf0:/data/temp# ./unskript-client.py -rr -h
usage: unskript-ctl [-h] [-lr] [-rr ...] [-rc RUN_CHECKS] [-df DISPLAY_FAILED_CHECKS] [-lc LIST_CHECKS] [-sa SHOW_AUDIT_TRAIL]
Welcome to unSkript CLI Interface VERSION: 0.1.0
optional arguments:
-h, --help            show this help message and exit
-lr, --list-runbooks  List Available Runbooks
-rr ..., --run-runbook ...
Run the given runbook RUNBOOK_NAME [-RUNBOOK_PARM1 VALUE1] etc.. …
```

Adding Runbook Parameter Support for interactive and non-interactive Runs

---

AWS/Change_AWS_Route53_TTL.ipynb
AWS/Change_AWS_Route53_TTL.json
AWS/legos/aws_get_ttl_for_route53_records/aws_get_ttl_for_route53_records.py
AWS/legos/aws_get_ttl_under_given_hours/aws_get_ttl_under_given_hours.json
AWS/legos/aws_get_ttl_under_given_hours/aws_get_ttl_under_given_hours.py

https://user-images.githubusercontent.com/110628398/233407188-cb3c5e0d-04f1-420a-a614-fa8df59c6952.mov

Runbook: Change AWS Route53 TTL

---

AWS/legos/aws_filter_unencrypted_s3_buckets/aws_filter_unencrypted_s3_buckets.json
AWS/legos/aws_list_unhealthy_instances_in_target_group/aws_list_unhealthy_instances_in_target_group.json

Action Next Hop parameter mapping fields filled with JQ expressions for legos: 
- Filter AWS Unencrypted S3 Buckets
- AWS List Unhealthy Instances in a Target Group
[EN-4458]: https://unskript.atlassian.net/browse/EN-4458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EN-4458: Action Next Hop Parameters with JQ expressions

---

.github/workflows/build-and-release-docker.yml

* Fixed Python version to 3.8
* Fixed urllib3 version to 1.26.6
* Fixed types-urllib3 version to 1.26.13
The issue by urllib3 version 2.x.y or higher has deprecated support for DEFAULT_CIPHERS. This is being used by boto3 and botocore libraries. The solution proposed over the internet to get over the DEFAULT_CIPHERS issue is to restrict the URLLIB to 1.26.6.  
Workflow URL: https://github.com/unskript/Awesome-CloudOps-Automation/actions/runs/4918223530 
Failed Workflow URL:  https://github.com/unskript/Awesome-CloudOps-Automation/actions/runs/4897777331/jobs …

Fix urllib3 issue

---

Postgresql/legos/postgresql_long_running_queries/postgresql_long_running_queries.py

f"pg_stat_activity.query_start) > interval {interval} seconds';"
to 
f"pg_stat_activity.query_start) > interval '{interval} seconds';"
adding the ' in front of {interval} allows this action to riun

BugFix: The long runningpostgres action was missing a single '  This resolves the error

---

AWS/legos/aws_terminate_ec2_instances/aws_terminate_ec2_instances.json

The action terminate AWS EC2 instances appears in the tool as "Terminate AWS Instances"
I changed the string to "Terminate AWS EC2 Instances" becuase that is clearer indication of what the action does.

updated action name in json

---

GCP/legos/gcp_save_csv_to_google_sheets_v1/gcp_save_csv_to_google_sheets_v1.py
Kubernetes/legos/k8s_get_cluster_health/k8s_get_cluster_health.py

There were 2 bugs in this action...
One was in line 67
for node in nodes.items():
changed to
for node in nodes.items:
2nd. The Action was not adding nodes over the threshold of memory and CPU properly, (it was adding one and overwriting it repeatedly) so I changed that logic to include ALL of the Actions over memory and CPU
Before:
after:

fixed broken action

---

GCP/legos/gcp_add_member_to_iam_role/gcp_add_member_to_iam_role.py
GCP/legos/gcp_add_role_to_service_account/gcp_add_role_to_service_account.py
GCP/legos/gcp_create_bucket/gcp_create_bucket.py
GCP/legos/gcp_create_filestore_instance/gcp_create_filestore_instance.py
GCP/legos/gcp_create_gke_cluster/gcp_create_gke_cluster.py
GCP/legos/gcp_create_service_account/gcp_create_service_account.py
GCP/legos/gcp_delete_bucket/gcp_delete_bucket.py
GCP/legos/gcp_delete_filestore_instance/gcp_delete_filestore_instance.py
GCP/legos/gcp_delete_object_from_bucket/gcp_delete_object_from_bucket.py
GCP/legos/gcp_delete_service_account/gcp_delete_service_account.py
GCP/legos/gcp_fetch_objects_from_bucket/gcp_fetch_objects_from_bucket.py
GCP/legos/gcp_get_instances_without_label/gcp_get_instances_without_label.py
GCP/legos/gcp_list_buckets/gcp_list_buckets.py
GCP/legos/gcp_list_compute_instances_by_label/gcp_list_compute_instances_by_label.py
GCP/legos/gcp_list_nodes_in_gke_cluster/gcp_list_nodes_in_gke_cluster.py
GCP/legos/gcp_list_public_buckets/gcp_list_public_buckets.py
GCP/legos/gcp_list_service_accounts/gcp_list_service_accounts.py
GCP/legos/gcp_remove_member_from_iam_role/gcp_remove_member_from_iam_role.py
GCP/legos/gcp_remove_role_from_service_account/gcp_remove_role_from_service_account.py
GCP/legos/gcp_resize_gke_cluster/gcp_resize_gke_cluster.py
GCP/legos/gcp_restart_compute_instances/gcp_restart_compute_instances.py
GCP/legos/gcp_stop_compute_instances/gcp_stop_compute_instances.py
GCP/legos/gcp_upload_file_to_bucket/gcp_upload_file_to_bucket.py

The execution flow is stopped now, if its an error, with the correct message.

Raise GCP actions error messages

---

Mongo/legos/mongodb_get_server_status/mongodb_get_server_status.py

Two issues:
- This check is not returning a list
- Mongo status had objects which were not serializable

Fix the get_server_status check

---

unskript-ctl/db_utils.py
unskript-ctl/unskript-client.py
unskript-ctl/unskript_config.yaml.template

[EN-5057] 
Adding support to declare Global Variables used in Checks in the `unskript_config.yaml` file. 
This PR adds a sample template for reference.
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/d3e70e23-f35d-4726-8bd4-6c57ac12febf
[EN-5058]: https://unskript.atlassian.net/browse/EN-5058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EN-5057]: https://unskript.atlassian.net/browse/EN-5057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …

Changes to use globals in the config yaml file as inputParamsJson

---

unskript-ctl/unskript-client.py

[EN-5056]
This PR brings in the fix that cleans up the Notebook Node before creating the temporary runbook
that gets run. 
`Cleaned up debugs and redundant display of results` 
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/afb95609-2bd7-487a-be5d-392fcb21ed2e
[EN-5056]: https://unskript.atlassian.net/browse/EN-5056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Traitlet error removal

---

AWS/Resize_PVC.ipynb

Changed action_needs_credentials false for 2 cells which are not required

EN-5097: Update Resize_PVC.ipynb

---

Kubernetes/legos/k8s_check_cronjob_pod_status/k8s_check_cronjob_pod_status.py
Kubernetes/legos/k8s_check_service_pvc_utilization/README.md
Kubernetes/legos/k8s_check_service_pvc_utilization/k8s_check_service_pvc_utilization.py
Kubernetes/legos/k8s_get_pods_in_crashloopbackoff_state/k8s_get_pods_in_crashloopbackoff_state.py

1. k8s_check_service_pvc_utilization check now has `namespace` and `service_name` as optional params. This enables the lego to run for all services. The code is optimized to reuse the utility pod for all services in a namespace.
2. crashloopbackoff check  now checks if `container_status` is not available.
3. Cronjob pod check was using batch/v1beta1 which was incompatible with unskript dev cluster version (it was working for lightbeam). Now we are using kubectl to fetch cronjobs.

Bug fixes for K8s checks

---

unskript-ctl/add_creds.py

Made server_url and realm as the only mandatory parameters,.

Change Keycloak schema and inputs in add_creds

---

unskript-ctl/unskript_ctl.py

```
(base) root@876a2ff59ed3:~# unskript-ctl.sh -rc --type k8s, postgres, kafka, redis
Executing Runbook -> /unskript/data/execution/workspace/25e31772-b139-4f64-a264-a520b2ae2de0.ipynb
INFO:traitlets:Executing notebook with kernel: python3
╒════════════════════════════════════════════════════════╤═══════════╤════════════════╤══════════════════════════════════════════════════════════════════════════════════╕
│ Checks Name                                            │ Result    │ Failed Count   │ Error …
```

Reading creds data from Global variable opposed to pss

---

unskript-ctl/config/unskript_ctl_config.yaml
unskript-ctl/unskript_ctl.py
unskript-ctl/unskript_ctl_config_parser.py

Audit files delete support
-  Dont error out if the config file processing fails
- Be more verbose
- Add audit period support.
- For k8s in cron, it needs to have the env variables, as kubectl uses them, so instead copying over all non-empty env variables to the cron job defintion.
- Invalid yaml file
```
(base) root@ddebc3651a02:~# python /usr/local/bin/unskript_ctl_config_parser.py
Parsing config file /etc/unskript/unskript_ctl_config.yaml failed
```
- Yaml file doesnt exist
```
(base) root@ddebc3651a02:~# python /usr/local/bin/unskript_ctl_config_parser.py
/etc/unskript/unskript_ctl_config.yaml Not found!
```
Good case
```
(base) root@ddebc3651a02:~# python /usr/local/bin/unskript_ctl_config_parser.py
###################################
Processing global section …
```

Amit-k8s-support

---

unskript-ctl/config/unskript_ctl_config.yaml
unskript-ctl/unskript_ctl.py
unskript-ctl/unskript_ctl_config_parser.py
unskript-ctl/unskript_ctl_gen_report.py

- Support for matrix arguments.
- Support for email subject line
- Multiple namespace (lightbeam, unskript) run
```
╒════════════════════════════════════════════════════════╤══════════╤════════════════╤═════════╕
│ Checks Name                                            │ Result   │   Failed Count │ Error   │
╞════════════════════════════════════════════════════════╪══════════╪════════════════╪═════════╡
│ Get Kubernetes PODS with high restart                  │  PASS    │              0 │ N/A     │
├────────────────────────────────────────────────────────┼──────────┼────────────────┼─────────┤
│ Get K8S Service with no associated endpoints           │  FAIL    │              1 │ N/A     │
├────────────────────────────────────────────────────────┼──────────┼────────────────┼─────────┤
│ …
```

Amit en 5152 multiple namespace

---

unskript-ctl/README.md
unskript-ctl/unskript_ctl.py
unskript-ctl/unskript_ctl_config_parser.py

Support for multiple scripts
One bad command and one good
```
(base) root@7ad279f11993:~# /usr/local/bin/unskript-ctl.sh -r --script "lf -p; df -kh"
Executing script lf -p; df -kh
OUTPUT FILE: /unskript/data/execution/unskript_script_run_output-2023-11-07T06_08_29.881419/unskript_script_run_output.txt
(base) root@7ad279f11993:~# cat /unskript/data/execution/unskript_script_run_output-2023-11-07T06_08_29.881419/unskript_script_run_output.txt
/bin/sh: 1: lf: not found
Filesystem      Size  Used Avail Use% Mounted on
overlay          59G   36G   20G  65% /
tmpfs            64M     0   64M   0% /dev
tmpfs           3.0G     0  3.0G   0% /sys/fs/cgroup
shm              64M     0   64M   0% /dev/shm
/dev/vda1        59G   36G   20G  65% /etc/hosts
tmpfs           3.0G     0  3.0G   0% …
```

multiple script support

---

Redis/legos/redis_list_large_keys/redis_list_large_keys.py

Decode key from bytes to a string before using it as a key in dict as it is not serializable.

Fix: Decode key for Redis large keys check

---

Kubernetes/legos/k8s_check_service_pvc_utilization/k8s_check_service_pvc_utilization.py

Using mount paths to check pvc utilization for services

Fix: K8s PVC utilization check

---

Kubernetes/legos/k8s_detect_service_crashes/k8s_detect_service_crashes.py

```
(base) root@awesome-awesome-runbooks-0:~/checks# python ./k8s_detect_service_crashes_new.py 
Using incluster config
POD kafka-ui-558c57f65f-6cxt7 CONTAINER kafka-ui
POD ingress-kong-69fdcf9b7c-x2j4t CONTAINER proxy
POD ingress-kong-69fdcf9b7c-x2j4t CONTAINER ingress-controller
POD lb-argo-workflows-server-5dd6b9956b-57h9s CONTAINER argo-server
POD lb-kafka-connect-5c6846cdbd-jkx2k CONTAINER kafka-connect
POD lb-keycloak-0 CONTAINER keycloak
POD lb-redis-master-0 CONTAINER redis
POD lb-redis-replicas-0 CONTAINER redis
POD lb-redis-replicas-1 CONTAINER …
```

Seperating out detect service crash as separate PR

---

unskript-ctl/config/unskript_ctl_config.yaml
unskript-ctl/unskript_ctl_config_parser.py

Added support for scheduling remote debugging.
```
remote_debugging:
enable: true
ovpn_file: "/tmp/client-abc.ovpn"
#
tunnel_up_cadence: "42 23 * * *"
tunnel_down_cadence: "43 23 * * *"
#
```
Related crontab entry
```
0 0 * * * /opt/conda/bin/python /usr/local/bin/unskript_audit_cleanup.py
42 23 * * * /usr/local/bin/unskript-ctl.sh --debug --start --config /tmp/client-abc.ovpn
43 23 * * * /usr/local/bin/unskript-ctl.sh --debug --stop
```

remote debugging schedule option

---

unskript-ctl/unskript_ctl_config_parser.py
unskript-ctl/unskript_ctl_main.py

The unskript-ctl changes had to be percolated to config_parser.py too, which was missed in the main PR.
This PR brings in the change for that.
```
root@e859cf63c01a:/# ./start.sh 
* Starting periodic command scheduler cron                                                                                                         [ OK ] 
###################################
Processing global section
###################################
Global: audit period 90 days
###################################
Processing checks section
###################################
###################################
Processing credential section …
```

Fixed config parser and debug option

---

unskript-ctl/unskript_ctl_main.py

It was failing while 
```
root@92a22155aa18:~# unskript-ctl.sh debug start  --config /tmp/client-abc.ovpn
ERROR: Not able to find the configuration to start debug session
root@92a22155aa18:~# 
```
After fix
```
root@92a22155aa18:~# unskript-ctl.sh debug start  --config /tmp/client-abc.ovpn
Successfully Started the Debug Session
```

bugfix/EN-5229 : Update unskript_ctl_main.py

---

unskript-ctl/config/unskript_ctl_config.yaml
unskript-ctl/unskript_ctl_config_parser.py
unskript-ctl/unskript_ctl_main.py
unskript-ctl/unskript_ctl_upload_session_logs.py

```
Whenever a terminal is opened, script starts capturing the session logs.
When the user types exit or close the window, the script session log file becomes available. It will be stored at /var/unskript/sessions/logs/<sessiod_id>.log
We need to upload these logs to RTP via the ovpn tunnel.
Write a standalone python script which creates a tar of the logs in the /var/unskript/sessions/logs/ directory and calls the RTP upload endpoint.
Its possible that some file get added into this directory after the tar is done and while upload is happening, so to cover that case, move the files (not copy) in this directory in some other directory (name it like upload ) and do the tar of that.
If the upload succeeds, delete the files in the upload directory.
If the upload fails, keep the files in the …
```

EN-5227 : Session Logs Upload from Client

---

unskript-ctl/unskript_ctl_upload_session_logs.py

Fix: [EN-5252](https://unskript.atlassian.net/browse/EN-5252)
Move logs from completed-logs to uploads when doing upload
[EN-5252]: https://unskript.atlassian.net/browse/EN-5252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EN-5252: Ensure terminal session is completed before upload

---

unskript-ctl/unskript_ctl_notification.py
unskript-ctl/unskript_utils.py

Fixes [EN-5277]
* Includes Failed object inline 
* If the Failed object character count is more than 20000 (roughly 250 lines) then we send as attachment.
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/b44be918-7346-4ae9-b083-d6e2b1e668a3
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/cce96601-a0e2-40db-9d5d-08fe1bf1a096
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/990839af-c87e-4f6b-a16d-8525f2413ef5 …

Inline display of failed objects

---

Kafka/legos/kafka_check_lag_change/kafka_check_lag_change.py

1. Added a try catch block to finally close the consumer when not needed. 
2. Fetching topic partitions before creating consumers
3. Using ThreadPoolExecutor to execute the task concurrently. 
Before:
After:

Fix kafka check lag change action

---

unskript-ctl/config/unskript_ctl_config.yaml
unskript-ctl/templates/template_script.j2
unskript-ctl/unskript_ctl_run.py

* Implemented  `per check timeout` 
* When a check is started to execute, a Poll timer is set, at the timer expiring, if the check is still not completed, it is interrupted and declared `ERROR` with the reason `Check time out` 
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/688018f5-f710-4a0c-be6a-dd17e27511a8
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/0a8ada0a-d527-47c7-b8ae-9d4c7890e560

Per Check Timeout support

---

unskript-ctl/templates/template_script.j2

* Reset SIGALRM after running all the checks, this is essential if any other operation follows running checks, like `--info` or `--script`
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/573604bd-5dd5-4314-be4e-6dac69d2e740
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/92d9d47d-4d7d-4bb2-9345-a661e9c11949

Disable Timeout Restriction after all checks are run

---

Kafka/legos/kafka_check_lag_change/kafka_check_lag_change.py
Kubernetes/legos/k8s_check_service_status/k8s_check_service_status.py

1. Make endpoints as a required parameter
2. Update fetch_leg function call
Error:
Fail:
Pass:

Minor changes for k8s service endpoints and kafka lag check lego

---

Kubernetes/legos/k8s_get_memory_utilization_of_services/k8s_get_memory_utilization_of_services.py

* Changed the logic of getting the utilization. 
* The logic implemented is to get the `kubectl top pods -n <namespace>` and iterate each of the pods listed in it to get the resource limit
* Compute the memory utliization based on (mem_usage / mem_limit * 100)
```
root@awesome-awesome-runbooks-0:~# unskript-ctl.sh run check --name k8s_get_memory_utilization_of_services
Running: 100%|████████████████████████████████████████████████████████| 3/3 [00:31<00:00, 10.50s/it]
╒═══════════════════════════════════════════════╤══════════╤════════════════╤═════════╕
│ …
```

Fixed compute logic of memory utilization based on top pods only

---

unskript-ctl/unskript_ctl_database.py
unskript-ctl/unskript_ctl_main.py
unskript-ctl/unskript_ctl_run.py

* Before priority check support running of `info legos` was using `name` as `action_entry_function`
* When priority checks support was added the running of info legos got impacted because it was still looking for `name`. Changed the logic to form the checks based on action_entry_function list rather than `name` 
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/b4ef892f-a8c9-4458-88d5-be83bafa8985
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/37ddd440-c865-4654-a9fa-160d3a891a96 …

Fixed regression when running info legos

---

Kubernetes/legos/k8s_get_memory_utilization_of_services/k8s_get_memory_utilization_of_services.py
unskript-ctl/unskript_ctl_database.py

1.  Need to handle None type in the convert_memory_to_bytes function
```
k8s:Get K8s services exceeding memory utilization convert_memory_to_bytes function
Failed Objects:
'@beartyped check_4.convert_memory_to_bytes() parameter memory_value="None" violates
type hint <class ''str''>, as "None" not instance of str.'
```
2. Updated the update method to accept byte type object instead of assuming it is dict and added type check.
```
Traceback (most recent call last):
File "/usr/local/bin/./unskript_ctl_main.py", line 740, in <module>
main()
File "/usr/local/bin/./unskript_ctl_main.py", line 719, in main
uc.run_main(args=args, parser=parser)
File "/usr/local/bin/./unskript_ctl_main.py", line 137, in run_main
self.update_audit_trail(collection_name='audit_trail', status_dict_list=status_of_run) …
```

Fix: update method in unskript_ctl_db

---

.github/workflows/build-and-release-docker-lite.yml
unskript-ctl/unskript_ctl_notification.py
unskript-ctl/unskript_ctl_run.py

* Fixed printing of Results for info legos that were jumbled 
```
root@awesome-awesome-runbooks-0:~# unskript-ctl.sh run --info
2024-02-19 21:26:57,902 - UnskriptCtlLogger - INFO - No Actions found for these names: ['k8s_get_versioning_info_wrong_one']
root@awesome-awesome-runbooks-0:~# vi /etc/unskript/unskript_ctl_config.yaml 
root@awesome-awesome-runbooks-0:~# unskript-ctl.sh run --info
2024-02-19 21:27:13,416 - UnskriptCtlLogger - INFO - No Information gathering action mentioned in the config file!
root@awesome-awesome-runbooks-0:~# 
```
``` …
```

Fixed issue with jumbled printing of results

---

Kafka/legos/kafka_get_topics_with_lag/kafka_get_topics_with_lag.py
unskript-ctl/config/unskript_ctl_config.yaml

* Diff provided by @amit-chandak-unskript  
```
root@awesome-awesome-runbooks-0:~/test# time python ./kafka_test.py 
LENGTH OF CONSUMER_GROUPS: 5
Max Topics 63
Max Parition 32
Sum of Topics 315
Sum of Partition 765
real	0m38.206s
user	0m1.441s
sys	0m0.231s
root@awesome-awesome-runbooks-0:~/test# 
```
```
root@awesome-awesome-runbooks-0:~/test# time python ./kafka_test.py 
LENGTH OF CONSUMER_GROUPS: 100
Max Topics 63
Max Parition 32
Sum of Topics 6300
Sum of Partition 15300
real	2m19.458s
user	0m16.369s
sys	0m2.976s
```
Make sure that you have documented …

Optimize Kafka Get Topic With Lag 

---

Kubernetes/legos/k8s_check_service_pvc_utilization/k8s_check_service_pvc_utilization.py

Fixes [EN-5324]
* While getting the pod name based of service label, the regression that was caused was by indexing with a specific index, like 0. It would be safer to index it with `*`.
```
root@awesome-awesome-runbooks-0:~/test# unskript-ctl.sh run check --name k8s_check_service_pvc_utilization
Running: 100%|████████████████████████████████████████████████████████| 3/3 [00:04<00:00,  1.50s/it]
╒═══════════════════════════════════╤══════════╤════════════════╤═════════╕
│ Checks Name                       │ Result   │   Failed Count │ Error   │ …
```

Adding * for index to get metadata name

---

unskript-ctl/templates/first_cell_content.j2
unskript-ctl/templates/template_info_lego.j2
unskript-ctl/templates/template_script.j2
unskript-ctl/templates/timeout_handler.j2
unskript-ctl/unskript_ctl_run.py

* Change timeout logic for checks. Moved away from signal.alarm to decorator based timeout
* Info legos also has the timeout logic 
[temp_info_lego_test.txt](https://github.com/unskript/Awesome-CloudOps-Automation/files/14491942/temp_info_lego_test.txt)

Timeout per check enforcement

---

unskript-ctl/templates/template_script.j2
unskript-ctl/unskript_ctl_run.py

Fixes [EN-5340] [EN-5341]
This PR brings in two important fixes
* Timed out check listing in the report with the Count of errored checks
* Failed object to the check name was not considering the priority order 
```
root@awesome-awesome-runbooks-0:~# unskript-ctl.sh run check --type postgres --report
Running: 100%|████████████████████████████████████████████████████████| 7/7 [02:02<00:00, 17.43s/it]
╒════════════════════════════════════════╤══════════╤════════════════╤═════════════════════════════╕
│ Checks Name                            │ Result   │ …
```

En 5340 timeout checks in report

---

unskript-ctl/unskript_ctl_notification.py
unskript-ctl/unskript_utils.py

This PR brings Two things
* Fixed the logic the flag error when create_tarball_archive 
* Reduced The Max character count to 10 so that everytime the failed object is sent as email attachment. 
```
unskript@awesome-awesome-runbooks-0:~$ unskript-ctl.sh run check --type vault,postgres --info --script /tmp/hello.sh --report
Running: 100%|████████████████████████████████████████████████████████| 8/8 [00:01<00:00,  6.09it/s]
╒════════════════════════════════════════╤══════════╤════════════════╤═════════════════════════════╕
│ Checks Name …
```

Fixed the logic for sending notification

---

Kubernetes/legos/k8s_get_all_resources_utilization_info/k8s_get_all_resources_utilization_info.py

1. Feedback received: the latest report looks good but I see an error in at few places: `Error occurred while fetching pod utilization:` Please check.
2. Removed pods that are in Suceeded, Completed and Failed state.

Remove print statement from resource utilization info lego

---

unskript-ctl/unskript_ctl_run.py

* Adds `check_entry_function` to the execution output file.
```
unskript@awesome-awesome-runbooks-0:/unskript/data/execution$ cat 9f0d1fbb-2df0-420c-89d3-ad308cca262a_output.txt | jq | more
[
{
"status": 1,
"objects": null,
"error": "",
"id": "159ba9d99a6a388a1a0ec2b9462f4c1437beeca771a2ddd62cd9cbd32d3293c9",
"name": "Get Kafka broker health",
"check_entry_function": "kafka_broker_health_check"
},
{
"status": 1,
"objects": null,
"error": "",
"id": "99cafafecb730b73c1ea9a17d43e307ad2ee22e539d79b856f16dc074bf98dd7",
"name": "Get Kafka topic partition health", …
```

Adding check_entry_function to output so that diagnostic script can use it

---

unskript-ctl/templates/last_cell_content.j2
unskript-ctl/templates/template_script.j2
unskript-ctl/unskript_ctl_factory.py
unskript-ctl/unskript_ctl_run.py

[EN-5391]
* Fixed an issue that timeout-checks were not included in reports
* Fixed issue about listing the Checks with results based on the priority checks
```
unskript@awesome-awesome-runbooks-0:~/test$ unskript-ctl.sh run check --type kafka --script /tmp/hello.sh  --report
Running: 100%|████████████████████████████████████████████████████████| 6/6 [00:06<00:00,  1.17s/it]
╒════════════════════════════════════╤══════════╤════════════════╤═════════════════╕
│ Checks Name                        │ Result   │   Failed Count │ Error           │ …
```

Fixed issue with timedout checks skipping in report

---

unskript-ctl/templates/last_cell_content.j2
unskript-ctl/unskript_ctl_factory.py
unskript-ctl/unskript_ctl_run.py

* The index overflow happened because the result was double accounted for Failed and Errored case. 
* There was also an issue with fmt string when logging. Fixed that too
```
unskript@awesome-awesome-runbooks-0:~$ unskript-ctl.sh run check --type k8s,vault,postgres,redis,kafka,elasticsearch,mongodb --info --script /tmp/hello.sh --report
Running: 100%|████████████████████████████████████████████████████| 105/105 [04:35<00:00,  2.62s/it]
╒══════════════════════════════════════════════════════╤══════════╤════════════════╤════════════════════════════════════════ …
```

Fixed UT fixes for missing checks in report

---

unskript-ctl/diagnostics.py
unskript-ctl/unskript_ctl_main.py

Fixes [EN-5397]
* This PR brings in `diagnostics.py` which takes three inputs
* YAML File (Configuration file)
* Failed Objects file 
* Output directory path where the diagnostics output to be stored
[EN-5397]: https://unskript.atlassian.net/browse/EN-5397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding diagnostics support to be called by unskript_ctl

---

Kubernetes/legos/k8s_get_oomkilled_pods/k8s_get_oomkilled_pods.py
Kubernetes/legos/k8s_get_pods_with_high_restart/k8s_get_pods_with_high_restart.py
unskript-ctl/diagnostics.py
unskript-ctl/templates/last_cell_content.j2
unskript-ctl/unskript_ctl_run.py

Fixes [EN-5354] [EN-5383]
* Added time based check before declaring a check is passed or failed.
```
unskript@awesome-awesome-runbooks-0:~$ unskript-ctl.sh run  check --name k8s_get_oomkilled_pods 
Running: 100%|████████████████████████████████████████████████████████| 6/6 [00:05<00:00,  1.20it/s]
╒════════════════════════╤══════════╤════════════════╤═════════╕
│ Checks Name            │ Result   │   Failed Count │ Error   │
╞════════════════════════╪══════════╪════════════════╪═════════╡
│ Get K8S OOMKilled Pods │  FAIL    │              1 │ N/A     │ …
```

Modified Logic of checks to consider time based interval to declare check result

---

Kubernetes/legos/k8s_get_all_resources_utilization_info/k8s_get_all_resources_utilization_info.py

As per feedback:
1. Show only failed and Unknown jobs
2. Remove PVC info
- Namespace without any jobs
```
unskript@awesome-awesome-runbooks-0:/tmp/jit$ python jit_info_script3.py
Using incluster config
Pods:
+--------------+------------------------------------------+---------+---------------+-------------------+
|  Namespace   |                   Name                   | Status  | CPU Usage (m) | Memory Usage (Mi) |
+--------------+------------------------------------------+---------+---------------+-------------------+
| cert-manager |      cert-manager-584f85f6cf-nll6v       | Running |      1m       |       35Mi        |
| cert-manager | cert-manager-cainjector-6c58576757-bqgqj | Running |      1m       |       63Mi        |
| cert-manager |  cert-manager-webhook-75d68f6fb9-7pwnl   | …
```

Update all_resources_utilization info lego

---

Kubernetes/legos/k8s_get_all_resources_utilization_info/k8s_get_all_resources_utilization_info.py
Kubernetes/legos/k8s_get_error_pods_from_all_jobs/k8s_get_error_pods_from_all_jobs.py
Kubernetes/legos/k8s_get_oomkilled_pods/k8s_get_oomkilled_pods.py
Kubernetes/legos/k8s_get_pods_with_high_restart/k8s_get_pods_with_high_restart.py

1. Getting this error while running k8s_get_error_pods_from_all_jobs check:
`- module 'kubernetes.client' has no attribute 'models'`
Which was permeating to other checks run after this check.
Resolved it by using kubectl instead of kubernetes python client for check implementation
2. Add termination time and interval time to oomkilled pods and high restart pods check
- Using jit script
```
(unskript) unskript@lb-unskript-0:/tmp$ python jit_script.py
Using incluster config
JOB NAME: kong-migrations
JOB NAME: lb-bloom-filter-builder-28547640
PODS IN JOB lb-bloom-filter-builder-28547640: lb-bloom-filter-builder-28547640-7prn6
JOB NAME: lb-bloom-filter-builder-28548000
PODS IN JOB lb-bloom-filter-builder-28548000: lb-bloom-filter-builder-28548000-27zhj
JOB NAME: …
```

Update check error pods from all jobs to use kubectl

---

Kubernetes/legos/k8s_get_cluster_health/k8s_get_cluster_health.py
Mongo/legos/mongodb_compare_disk_size_to_threshold/mongodb_compare_disk_size_to_threshold.py
Postgresql/legos/postgresql_get_cache_hit_ratio/postgresql_get_cache_hit_ratio.json
Postgresql/legos/postgresql_get_server_status/postgresql_get_server_status.py

[EN-5441](https://unskript.atlassian.net/browse/EN-5441)
```
unskript@lb-unskript-0:/tmp$ python test.py
Using incluster config
Checking pod health across namespaces: ['lightbeam']
Namespace: lightbeam
Service: lightbeam-api-gateway
Label Selector for lightbeam-api-gateway: app=lightbeam-api-gateway
Total pods found for lightbeam-api-gateway: 1
Running pods for lightbeam-api-gateway: 1
Running percentage for lightbeam-api-gateway: 100.0%
Service: lb-argo-workflows-server
Label Selector for lb-argo-workflows-server: app.kubernetes.io/component=server,app.kubernetes.io/name=argo-workflows
Total pods found for lb-argo-workflows-server: 1
Running pods for lb-argo-workflows-server: 1
Running percentage for lb-argo-workflows-server: 100.0%
Service: lightbeam-frontend
Label Selector for …
```

Update logic of K8s cluster health check 

---

unskript-ctl/unskript_ctl_notification.py

Fixes [EN-5491]
This PR Brings in support for 
* Multiple Email receipient specification in the YAML file  Like this
```
provider: SES  # (OR SMTP or Sendgrid)
SMTP:
smtp-host: ${SMTP_HOST}
smtp-user: ${SMTP_USERNAME}
smtp-password: ${SMTP_PASSWORD}
to-email: 
- YYY@unskript.com
- XXX@unskript.com
from-email: "no-reply@unskript.com"
SES:
access_key: ${ACCESS_KEY}
secret_acess: ${SECRET_ACCESS}
region: us-west-2
to-email: 
- XXX@unskript.com
- YYY@unskript.com
from-email: no-reply@unskript.com
Sendgrid:
api_key: ${SENDGRID_API_KEY} 
to-email: 
- XXX@unskript.com
- YYY@unskript.com
from-email: no-reply@unskript.com
```
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what …

Adding multiple email support

---

unskript-ctl/templates/template_script.j2
unskript-ctl/unskript_ctl_run.py

[EN-5503](https://unskript.atlassian.net/browse/EN-5503)
[unSkript, Inc. Mail - Sandbox - Daily scan progress report and Cluster health status_.pdf](https://github.com/unskript/Awesome-CloudOps-Automation/files/15235935/unSkript.Inc.Mail.-.Sandbox.-.Daily.scan.progress.report.and.Cluster.health.status_.pdf)
- Tested on Sandbox cluster (not scaled up)
- Timeout 60 seconds
[EN-5503]: https://unskript.atlassian.net/browse/EN-5503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix unskript-ctl matrix execution and merging of check outputs

---

unskript-ctl/unskript_ctl_notification.py

[EN-5534](https://unskript.atlassian.net/browse/EN-5534)
[EN-5534]: https://unskript.atlassian.net/browse/EN-5534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bring back script run status

---

unskript-ctl/unskript_ctl_main.py
unskript-ctl/unskript_ctl_run.py
unskript-ctl/unskript_upload_results_to_s3.py

[EN-5468](https://unskript.atlassian.net/browse/EN-5468)
[EN-5465](https://unskript.atlassian.net/browse/EN-5465)
The idea is that the customer wants to see all the clusters reports summary on a dashboard. We need a common repository to store this data which then unctl container will pick.
Email will not be needed once we have the dashboard.
Uploaded checks output for Sanbox cluster and Internal Cluster. 
```
unskript@lb-unskript-0:~/test$ python ./upload.py 
unskript@lb-unskript-0:~$cd;  ls
test  unskript_ctl.log
unskript@lb-unskript-0:~$ tail unskript_ctl.log 
2024-05-29 22:37:10 : Uploading file /home/unskript/test/run_directory/metadata.txt to lightbeam-reports/local_test/2024/05/29/metadata.txt
2024-05-29 22:37:10 : File /home/unskript/test/run_directory/metadata.txt uploaded …
```

Upload failed objects JSON to S3

---

ElasticSearch/legos/elasticsearch_get_index_health/elasticsearch_get_index_health.py
unskript-ctl/unskript_ctl_main.py
unskript-ctl/unskript_upload_results_to_s3.py

* Fixes for build 1.5.54 
* Fetch health endpoint and add condition to check health of index- check: elasticsearch_get_index_health

Fixes found while testing 1.5.54 build

---

unskript-ctl/unskript_upload_results_to_s3.py

Found an issue where the bucket existence was not being verified, so added a check to do that

Add bucket exists check before uploading to S3

---

unskript-ctl/unskript_ctl_run.py

* Refactored output_after_merge function
```
unskript@lb-unskript-0:~$ unskript-ctl.sh run check --type k8s --script "/usr/local/bin/lb_reports.sh" 
WARNING:ZODB.FileStorage:Ignoring index for /var/unskript/snippets.db
Running: 100%|██████████████████████████████████████████████████████| 83/83 [03:09<00:00,  2.28s/it]
Traceback (most recent call last):
File "/usr/local/bin/./unskript_ctl_main.py", line 772, in <module>
main()
File "/usr/local/bin/./unskript_ctl_main.py", line 749, in main
uc.run_main(args=args, parser=parser)
File …
```

Refactoring output after merge function

---

unskript-ctl/config/unskript_ctl_config.yaml
unskript-ctl/unskript_ctl_main.py
unskript-ctl/unskript_ctl_notification.py

Fixes [EN-5684]
This PR Brings in support for
* Email retrial (Max 5 times with exponential backoff support)
* Inclusion of unskript_ctl.log file in the email archive
* Improved compression with `J` option to help reduce the email attachment file size
```
unskript@awesome-awesome-runbooks-0:~$ unskript-ctl.sh run check --type vault --report
Running: 100%|████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.09it/s]
╒══════════════════════════╤══════════╤════════════════╤═════════╕
│ Checks Name              │ Result   │   Failed Count │ Error   │ …
```

Email Retries and Log file inclusion in the attachment
