AWS/README.md, Kubernetes/README.md, Mongo/README.md, Postgresql/README.md, README.md
=> Updating README files

AWS/legos/aws_delete_volume/README.md, AWS/legos/aws_filter_ec2_by_tags/README.md, AWS/legos/aws_filter_unattached_ebs_volume/README.md, AWS/legos/aws_filter_untagged_ec2_instances/README.md, AWS/legos/aws_get_instance_details/README.md, Jira/legos/jira_issue_change_status/README.md, Jira/legos/jira_issue_change_status/jira_issue_change_status.json, Jira/legos/jira_issue_change_status/jira_issue_change_status.py, Kubernetes/Rollback-k8s-Deployment-and-Update-Jira.ipynb, Kubernetes/legos/k8s_kubectl_rollout_deployment/README.md, Kubernetes/legos/k8s_kubectl_rollout_deployment/__init__.py, Kubernetes/legos/k8s_kubectl_rollout_deployment/k8s_kubectl_rollout_deployment.json, Kubernetes/legos/k8s_kubectl_rollout_deployment/k8s_kubectl_rollout_deployment.py
Rollback k8s deployment and update Jira issue status
=> EN-3093 - Rollback k8s deployment and update Jira

.github/DEVELOPERGUIDE.md, README.md
Added Developer Guide and link to README.md for the Developer Guide
N/A
N/A
=> Adding DEVELOPERGUIDE and link in README

AWS/.gitignore, AWS/Add-new-IAM-user.ipynb
added a gitignore so I don't add those darn DS_store files.
made grammatical changes to the add IAM user runbook
=> added gitignore and edited one xrunbook

.github/guidelines-to-creating-runbook.md, README.md
Adding guideline to create a runbook.
=> Adding Guideline to create a runbook

.github/PULL_REQUEST_TEMPLATE/LEGO_PR_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE/RUNBOOK_PR_TEMPLATE.md
Added Runbook PR Template. Renamed Existing template to LEGO_PR_TEMPLATE.
=> Added Runbook PR Template 

README_template.md
instructions were incorrect -updated url to access new runbook
=> fixed url on creating runbook

ElasticSearch/legos/elasticsearch_check_health_status/README.md, ElasticSearch/legos/elasticsearch_check_health_status/elasticsearch_check_health_status.json, ElasticSearch/legos/elasticsearch_check_health_status/elasticsearch_check_health_status.py, ElasticSearch/legos/elasticsearch_list_allocations/README.md, ElasticSearch/legos/elasticsearch_list_allocations/elasticsearch_list_allocations.json, ElasticSearch/legos/elasticsearch_list_allocations/elasticsearch_list_allocations.py, ElasticSearch/legos/elasticsearch_list_nodes/README.md, ElasticSearch/legos/elasticsearch_list_nodes/elasticsearch_list_nodes.json, ElasticSearch/legos/elasticsearch_search_query_new/elasticsearch_search_query_new.json, ElasticSearch/legos/elasticsearch_search_query_new/elasticsearch_search_query_new.py
Cleaning up ES Files that had GIT Conflict lines in it
=> Cleaning up ES Files

AWS/Update_and_Manage_AWS_User_Permission.ipynb
the edited xrunbook had an error.  "attache" -> "attach" and now the runbook works....
=> spelling  error broke runbook

README.md
Formated docker command
- [x ] My changes generate no new warnings.
=> Formated docker command

SSH/legos/ssh_execute_remote_command/ssh_execute_remote_command.py
Remove extra new line from ssh lego.
Verified the output using pytest
```
=================================================================================================================== test session starts ==================================================================================================================== …
```
=> Remove extra new line from ssh lego

SSH/legos/ssh_execute_remote_command/ssh_execute_remote_command.py
=> parametrize proxy host for ssh lego

SalesForce/legos/salesforce_assign_case/salesforce_assign_case.json, SalesForce/legos/salesforce_case_change_status/salesforce_case_change_status.json, SalesForce/legos/salesforce_create_case/salesforce_create_case.json, SalesForce/legos/salesforce_delete_case/salesforce_delete_case.json, SalesForce/legos/salesforce_get_case/salesforce_get_case.json, SalesForce/legos/salesforce_get_case_status/salesforce_get_case_status.json, SalesForce/legos/salesforce_get_handle/salesforce_get_handle.json, SalesForce/legos/salesforce_search_case/salesforce_search_case.json, SalesForce/legos/salesforce_update_case/salesforce_update_case.json
Please describe what the runbook is accomplishing. 
>  Eg: This Runbook helps in find and prune un-used keypairs in AWS
Please describe the parameters that are required to be filled when this runbook is run.
> Eg: This Runbook needs One parameter `region`
>    region: string : AWS Region where we need to search the un-used keypairs in.
Please include the list of checks this runbook has implemented. 
> Eg: This runbook implements health check for MongoDB Server.
=> Add json file for salesforce legos

.github/workflows/build-and-release-docker.yml
=> Adding Devops Branch

Grafana/legos/grafana_list_alerts/grafana_list_alerts.py
=> EN-3704-ts-grafana-not-all-alarms-are-pulled-in

AWS/Publicly_Accessible_Amazon_RDS_Instances.ipynb, AWS/legos/aws_delete_volume_by_id/aws_delete_volume_by_id.json, AWS/legos/aws_delete_volume_by_id/aws_delete_volume_by_id.py, AWS/legos/aws_filter_unattached_ebs_volume/README.md, AWS/legos/aws_filter_unattached_ebs_volume/aws_filter_unattached_ebs_volume.json, AWS/legos/aws_filter_unattached_ebs_volume/aws_filter_unattached_ebs_volume.py, AWS/legos/aws_get_alb_listeners_without_http_redirect/README.md, AWS/legos/aws_get_alb_listeners_without_http_redirect/aws_get_alb_listeners_without_http_redirect.json, AWS/legos/aws_get_alb_listeners_without_http_redirect/aws_get_alb_listeners_without_http_redirect.py, AWS/legos/aws_get_publicly_accessible_db_instances/README.md, AWS/legos/aws_get_publicly_accessible_db_instances/aws_get_publicly_accessible_db_instances.json, AWS/legos/aws_get_publicly_accessible_db_instances/aws_get_publicly_accessible_db_instances.py, AWS/legos/aws_list_application_loadbalancers/README.md, AWS/legos/aws_list_application_loadbalancers/aws_list_application_loadbalancers.json, AWS/legos/aws_list_application_loadbalancers/aws_list_application_loadbalancers.py, AWS/legos/aws_modify_listener_http_redirection/aws_modify_listener_http_redirection.json
Publicly Accessible Amazon RDS Instances
=> EN-3765 - Publicly Accessible Amazon RDS Instances

AWS/Copy_ami_to_all_given_AWS_regions.ipynb
Modify "Copy AMI to all AWS regions" Runbook description and parameters.
https://user-images.githubusercontent.com/63058785/204805941-030f6f2f-e5a0-4c4c-87b5-c3cc3f58b243.mp4
=> Modify "Copy AMI to all AWS regions" Runbook description and parameters.

AWS/Add_new_IAM_user.ipynb, AWS/Add_new_IAM_user.json
Adding a new IAM user in AWS and creating a login profile for the new user.
=> Runbook to Add new IAM user in AWS

AWS/legos/aws_get_alb_listeners_without_http_redirect/aws_get_alb_listeners_without_http_redirect.py
Detach Instance from Auto Scaling Group 
=> Spell mistake resolved

AWS/AWS_Access_Key_Rotation.ipynb
1. Changed Runbook and Actions description
2. Removed credentials metadata
3. Changed parameters from optional to required
https://user-images.githubusercontent.com/110628398/204539209-0c9a3529-91a7-4a0a-aa72-4bbf5d5475c3.mov
=> Access key Rotation Runbook

AWS/legos/aws_change_acl_permissions_of_buckets/aws_change_acl_permissions_of_buckets.json, AWS/legos/aws_change_acl_permissions_of_buckets/aws_change_acl_permissions_of_buckets.py
1. Added Enum to Modify ACL permission for S3 bucket lego
2. Modified json
=> Modify Change ACL Permissions Lego

AWS/legos/aws_filter_instances_without_termination_and_lifetime_tag/aws_filter_instances_without_termination_and_lifetime_tag.json, AWS/legos/aws_filter_instances_without_termination_and_lifetime_tag/aws_filter_instances_without_termination_and_lifetime_tag.py, AWS/legos/aws_filter_untagged_ec2_instances/aws_filter_untagged_ec2_instances.json, AWS/legos/aws_filter_untagged_ec2_instances/aws_filter_untagged_ec2_instances.py, AWS/legos/aws_filter_unused_keypairs/aws_filter_unused_keypairs.json, AWS/legos/aws_get_publicly_accessible_db_snapshots/aws_get_publicly_accessible_db_snapshots.json, AWS/legos/aws_get_schedule_to_retire_instances/aws_get_schedule_to_retire_instances.json, AWS/legos/aws_list_expiring_access_keys/aws_list_expiring_access_keys.json, AWS/legos/aws_list_expiring_acm_certificates/aws_list_expiring_acm_certificates.json
1. Removed typing from sub-function (EC2 Lifetime Tag lego)
2. Removed extra condition due to which lego was failing (Untagged EC2 Lego)
3. Added region as an optional param(Untagged EC2 Lego)
=> Bug fixes in check legos

AWS/Notify_about_unused_keypairs.ipynb
Added Checkoutput schema to check lego
https://user-images.githubusercontent.com/110628398/215512952-6872a20b-12a5-4ac0-89b4-dfeb48722d06.mov
=> Runbook: Notify Unused Keypairs

AWS/Renew_SSL_Certificate.ipynb
Added check lego with checklego output schema
Reference- N/A (Created this runbook for a SecOps meetup demo)
https://user-images.githubusercontent.com/110628398/215810399-921d3f94-f411-4e80-9e7f-cc738850b638.mov
=> Runbook: Renew SSL Certificates

AWS/Delete_Unattached_EBS_Volume.ipynb, AWS/legos/aws_filter_unattached_ebs_volume/aws_filter_unattached_ebs_volume.json
=> Runbook: Delete_Unattached_EBS_Volume

README_template.md
=> updating readme

AWS/Remediate_unencrypted_S3_buckets.ipynb
Remediate unencrypted S3 buckets
=> Runbook: Remediate unencrypted S3 buckets

.github/workflows/build-and-release-docker.yml
Changed Build instruction to streamline building individual components needed for the docker.
=> Fixing unskript build

README_template.md
=> Added import text

AWS/AWS_Access_Key_Rotation.ipynb
Changed check lego
Reference- SecOps meetup
https://user-images.githubusercontent.com/110628398/217508964-30479dea-7791-489b-a6af-66df73fe39fa.mov
=> Runbook: AWS Access Key Rotation

AWS/legos/aws_get_publicly_accessible_db_snapshots/aws_get_publicly_accessible_db_snapshots.json, AWS/legos/aws_get_publicly_accessible_db_snapshots/aws_get_publicly_accessible_db_snapshots.py
Check changes to return tuple, instead of CheckOutput.
Testing was attached to the corresponding unskript PR
=> Check changes to return Tuple

AWS/Delete_Unattached_EBS_Volume.ipynb, AWS/Detach_Instance_from_ASG.ipynb, AWS/Enforce_HTTP_Redirection_across_AWS_ALB.ipynb, AWS/Get_Aws_Elb_Unhealthy_Instances.ipynb, AWS/Publicly_Accessible_Amazon_RDS_Instances.ipynb, AWS/Publicly_Accessible_Amazon_RDS_Instances.json, AWS/Remediate_unencrypted_S3_buckets.ipynb
Publicly Accessible Amazon RDS Instances
=> EN-4032 Runbook: Publicly Accessible Amazon RDS Instances

Kubernetes/K8S_Pod_Stuck_In_CrashLoopBack_State.ipynb
Added a check lego to get all pods stuck in crashloopbackoff state.
Reference- Utility runbook. No specific reference.
https://user-images.githubusercontent.com/110628398/217821908-ccdaf352-69b7-43c0-96d4-575aafa5d47a.mov
=> Runbook: K8s pod stuck in CrashLoopBackOff State

Kubernetes/K8S_Pod_Stuck_In_CrashLoopBack_State.ipynb, Kubernetes/K8S_Pod_Stuck_In_ImagePullBackOff_State.ipynb
1. Updated runbook with check lego
2. Updated check lego of CrashloopbackOff runbook. 
https://user-images.githubusercontent.com/110628398/218298938-bb474bf9-ef91-442f-bb0c-c41c0fd0b021.mov
=> Runbook: K8s Pods Stuck in ImagePullBackOff state

Kubernetes/Get_Kube_System_Config_Map.ipynb
1. Changed description of legos
=> Runbook: Get Kube System Config Map 

AWS/Stop_Untagged_EC2_Instances.ipynb
1. Updated check lego
2. Updated notes
Runbook Source- Relay
https://user-images.githubusercontent.com/110628398/218944349-8ea5564b-0727-416a-9df8-5f886081fa5f.mov
[EN-3854]: https://unskript.atlassian.net/browse/EN-3854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Runbook: Stop Untagged EC2 Instances

Kubernetes/K8S_Log_Healthcheck.ipynb, Kubernetes/K8S_Log_Healthcheck.json
Added a new xRunBook to check K8s logs for warning messages.  It grabs all the pods in a namespace, and then gets all the logs, and looks for recent warning messages.
If there is a warning in the last x hours, alert the team via Slack.
=> added healthcheck runbook for K8s logs

AWS/Restart_Unhealthy_Services_Target_Group.ipynb
Check lego added with new scope changes
Source- Relay
https://user-images.githubusercontent.com/110628398/219112611-7a067b06-2306-4c80-9c64-769413562b1d.mov
[EN-3851]: https://unskript.atlassian.net/browse/EN-3851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Runbook: Restart Unhealhty Services in a target group

AWS/Configure_url_endpoint_on_a_cloudwatch_alarm.ipynb
Changes in description and nits.
=> Runbook: Configure URL Endpoint on a Cloudwatch Alarm

.github/workflows/run-legoschema.yml, AWS/legos/aws_get_service_quotas_v1/aws_get_service_quotas_v1.json
This workflow will run `make legoschema` at PR
=> Adding Legoschema build at PR

AWS/Run_EC2_from_AMI.ipynb
Run EC2 from AMI
https://user-images.githubusercontent.com/63058785/219436141-ad541e56-28e3-4068-a10f-9e24b90772fc.mp4
=> EN-3839 Runbook: Run EC2 from AMI

AWS/EC2_Disk_Cleanup.ipynb
=> EN-3834 Runbook: AWS EC2 Disk Cleanup

ElasticSearch/Elasticsearch_Rolling_Restart.ipynb
1. New elasticsearch legos added
2. Changed descriptions
3. Renamed legos and notes
https://user-images.githubusercontent.com/110628398/219598675-ee03055d-8f07-411a-b7d8-55dfce5ff3d1.mov
=> Runbook: Elasticsearch Rolling Restart

.github/scripts/unskript-client.py, .github/scripts/unskript-ctl.sh, .github/workflows/build-and-release-docker.yml, .github/workflows/run-legoschema.yml
Moved unskript-ctl to Awesome repo.
=> Moved unskript-ctl from unskript repo to Awesome repo

Kubernetes/K8S_Pod_Stuck_In_Terminating_State.ipynb
1. Changed execute kubctl legos
2. Changed descriptions of legos
=> Runbook: K8s Pod stuck in Terminating State

Kubernetes/Resize_List_of_PVCs.ipynb, Kubernetes/Resize_List_of_PVCs.json, Kubernetes/Resize_PVC.ipynb, Kubernetes/Resize_PVC.json
1. Changed faux legos to original
2. Improved the runbook with descriptions and notes
=> Runbooks: Resize PVC, Resize List of PVCs

Github/legos/github_get_handle/README.md, Github/legos/github_get_handle/github_get_handle.json, Github/legos/github_get_handle/github_get_handle.py
[EN-4110]: https://unskript.atlassian.net/browse/EN-4110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Lego: Get github handle

AWS/legos/aws_list_all_regions/aws_list_all_regions.py
Updated Get all regions command to default to us-west-2
=> Update AWS list all regions

.github/CONTRIBUTING.md
Corrected a typo in a link
no response
- [ ✓] My changes generate no new warnings.
- [✓ ] I have added tests that prove my fix is effective or that my feature works.
- [ ✓] Any dependent changes have been merged and published.
=> Corrected a typo in Contributing guidelines

Github/README.md
the Github action to generate readmes is failing because there is no readme in this directory.
Fixing by adding one
=> Create README.md for Github directory

Kubernetes/legos/k8s_kubectl_exec_command/k8s_kubectl_exec_command.py
=> fix the kubectl exec command in error

Kubernetes/K8S_Pod_Stuck_In_ImagePullBackOff_State.ipynb, Kubernetes/legos/k8s_kubectl_exec_command/k8s_kubectl_exec_command.py
=> Amit-fix-image-pullbackoff-runbook

.github/CONTRIBUTING.md, .github/DEVELOPERGUIDE.md, README_template.md, unskript-ctl/README.md
=> readme update

AWS/legos/aws_get_private_address_from_nat_gateways/aws_get_private_address_from_nat_gateways.json, Terraform/legos/terraform_exec_command/terraform_exec_command.py
=> Amit-remove-check-from-a-lego

.github/workflows/generate_readme.yaml, .github/workflows/lint-test.yaml
Adding Deleted workflow from Github/workflows directory.
=> Adding missing Workflow

Jira/legos/jira_assign_issue/jira_assign_issue.json, Jira/legos/jira_assign_issue/jira_assign_issue.py, Jira/legos/jira_create_issue/jira_create_issue.json, Jira/legos/jira_create_issue/jira_create_issue.py, Jira/legos/jira_get_issue/jira_get_issue.json, Jira/legos/jira_get_issue/jira_get_issue.py, Jira/legos/jira_get_issue_status/jira_get_issue_status.json, Jira/legos/jira_get_issue_status/jira_get_issue_status.py, Jira/legos/jira_issue_change_status/jira_issue_change_status.json, Jira/legos/jira_issue_change_status/jira_issue_change_status.py, Jira/legos/jira_search_issue/jira_search_issue.json, Jira/legos/jira_search_issue/jira_search_issue.py
=> Fix jira legos

Nomad/legos/nomad_get_handle/README.md, Nomad/legos/nomad_get_handle/nomad_get_handle.json, Nomad/legos/nomad_get_handle/nomad_get_handle.py
d and tested helm chart locally. 
=> Action: Nomad Get Handle

Netbox/legos/netbox_get_handle/README.md, Netbox/legos/netbox_get_handle/netbox_get_handle.json, Netbox/legos/netbox_get_handle/netbox_get_handle.py
Lego to get handle for netbox connector
=> Action: Netbox Get Handle

ChatGPT/legos/chatgpt_get_handle/README.md, ChatGPT/legos/chatgpt_get_handle/chatgpt_get_handle.json, ChatGPT/legos/chatgpt_get_handle/chatgpt_get_handle.py, Netbox/legos/netbox_get_handle/netbox_get_handle.json, Netbox/legos/netbox_list_devices/README.md, Netbox/legos/netbox_list_devices/netbox_list_devices.json, Netbox/legos/netbox_list_devices/netbox_list_devices.py, Nomad/legos/nomad_list_jobs/README.md, Nomad/legos/nomad_list_jobs/nomad_list_jobs.json, Nomad/legos/nomad_list_jobs/nomad_list_jobs.py
1. Get all jobs -Nomad
2. Get all devices - Netbox
3. Get handle- ChatGPT
=> Actions: Netbox,Nomad,ChatGPT

.github/workflows/sanitize-runbook.yml, sanitize.py
[EN-4412]
Adding Sanitize Runbook Workflow and Python Script
Here is the Workflow run. 
https://github.com/unskript/Awesome-CloudOps-Automation/actions/runs/4723691678
[EN-4412]: https://unskript.atlassian.net/browse/EN-4412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adding Sanitize Runbook

.github/workflows/generate_readme.yaml
=> Fix the generate_readme.yaml

AWS/Release_Unattached_AWS_Elastic_IPs.ipynb, AWS/Release_Unattached_AWS_Elastic_IPs.json, AWS/legos/aws_list_unattached_elastic_ips/aws_list_unattached_elastic_ips.json
https://user-images.githubusercontent.com/110628398/233340450-579148e2-98fc-4c52-9fbb-791176ecea8b.mov
=> Runbook: Release Unattached AWS Elastic IPs

AWS/Delete_EBS_Volumes_With_Low_Usage.ipynb, AWS/Delete_EBS_Volumes_With_Low_Usage.json, AWS/legos/aws_get_ebs_volume_for_low_usage/aws_get_ebs_volume_for_low_usage.json
https://user-images.githubusercontent.com/110628398/233448134-fa1124d8-e093-4f98-8a77-b5bbd3f44707.mov
=> Runbook: Delete EBS Volumes with Low Usage

README_extending_docker.md, README_template.md
Updated README.md to include the ACA_AWESOME_MODE option as an environment
variable when invoking Docker. This mode enables Automatic Sync of changes to credentials
and Runbooks to Host. 
```
docker run -it -p 8888:8888 \
-p 8050:8050 \
-v $HOME/.unskript:/unskript  \
-v $HOME/.data:/data  \
--user root \
-e ACA_AWESOME_MODE=1 \
unskript/awesome-runbooks:1105
```
```
Digest: sha256:06cddc3ba9862c8873f11361b98ce56c1489b575616ecea832c8e75af8b73fe2
Status: Downloaded newer image for unskript/awesome-runbooks:1105
_                                          
/ \__      _____  ___  ___  _ __ ___   ___  
/ _ \ \ /\ / / _ \/ …
```
=> Updating Launch command with the -e option for ACA_AWESOME_MODE

AWS/Delete_EBS_Volumes_With_Low_Usage.json
description and UUID were flipped in the JSON.
Fixed.
=> uuid and description were flipped

generate_readme.ipynb
Fixed the variable generation so that the urls all work.
=> fixed a couple of 404s in the generated action list

AWS/legos/aws_service_quota_limits/aws_service_quota_limits.json, AWS/legos/aws_service_quota_limits_vpc/aws_service_quota_limits_vpc.json, AWS/legos/aws_tag_ec2_instances/aws_tag_ec2_instances.json, GCP/legos/gcp_list_vms_access/gcp_list_vms_access.json, Kubernetes/legos/k8s_get_cluster_health/k8s_get_cluster_health.json, Stripe/legos/stripe_get_all_refunds/stripe_get_all_refunds.json, templates/legos/lego.json
There were 7 legos missing the action_categories entry in the JSON.
After this PR.. there will be none :D
=> last legos without categories

AWS/legos/aws_delete_rds_instance/README.md, AWS/legos/aws_delete_rds_instance/aws_delete_rds_instance.json, AWS/legos/aws_delete_rds_instance/aws_delete_rds_instance.py
=> Action: AWS Delete RDS Instance

ElasticSearch/Elasticsearch_Rolling_Restart.ipynb, Jenkins/Fetch_Jenkins_Build_Logs.ipynb, Kubernetes/Delete_Evicted_Pods_From_Namespaces.ipynb, Kubernetes/Get_Kube_System_Config_Map.ipynb, Kubernetes/K8S_Get_Candidate_Nodes_Given_Config.ipynb, Kubernetes/K8S_Pod_Stuck_In_CrashLoopBack_State.ipynb, Kubernetes/K8S_Pod_Stuck_In_ImagePullBackOff_State.ipynb, Kubernetes/K8S_Pod_Stuck_In_Terminating_State.ipynb, Kubernetes/Resize_List_of_PVCs.ipynb, Kubernetes/Resize_PVC.ipynb, Kubernetes/Rollback_k8s_Deployment_and_Update_Jira.ipynb, build/templates/GetStarted.ipynb, build/templates/Welcome.ipynb, build/templates/Welcome_template.ipynb, generate_readme.ipynb, sanitize.py
Fixed favicon path in all remaining ipynb files.
=> Updated path to favicon

ElasticSearch/Elasticsearch_Rolling_Restart.ipynb, Jenkins/Fetch_Jenkins_Build_Logs.ipynb, Jira/jira_visualize_time_to_resolution.ipynb, Kubernetes/Delete_Evicted_Pods_From_Namespaces.ipynb, Kubernetes/Get_Kube_System_Config_Map.ipynb, Kubernetes/K8S_Get_Candidate_Nodes_Given_Config.ipynb, Kubernetes/K8S_Log_Healthcheck.ipynb, Kubernetes/K8S_Pod_Stuck_In_CrashLoopBack_State.ipynb, Kubernetes/K8S_Pod_Stuck_In_ImagePullBackOff_State.ipynb, Kubernetes/K8S_Pod_Stuck_In_Terminating_State.ipynb, Kubernetes/Resize_List_of_PVCs.ipynb, Kubernetes/Resize_PVC.ipynb, Kubernetes/Rollback_k8s_Deployment_and_Update_Jira.ipynb, Postgresql/Postgresql_Display_Long_Running.ipynb, sanitize.py
=> Fix sanity issues in existing runbooks

AWS/Delete_Unused_NAT_Gateways.ipynb, AWS/Stop_Idle_EC2_Instances.ipynb
=> Amit fix sanity

Github/legos/github_get_pull_request/github_get_pull_request.py, Github/legos/github_get_team/github_get_team.py, Github/legos/github_get_user/github_get_user.py, Github/legos/github_invite_user_to_org/github_invite_user_to_org.py, Github/legos/github_issue_comment/github_issue_comment.py, Github/legos/github_list_open_issues/github_list_open_issues.py, Github/legos/github_list_org_members/github_list_org_members.py, Github/legos/github_list_pull_request_commits/github_list_pull_request_commits.py, Github/legos/github_list_pull_request_reviewers/github_list_pull_request_reviewers.py, Github/legos/github_list_pull_requests/github_list_pull_requests.py
I have fixed some Github file warnings
=> Fixing Github file warnings

.pylintrc
Introducing the pylintrc from google github style with some minor changes.
=> Fix pylintrc file

Kubernetes/legos/k8s_execute_local_script_on_a_pod/README.md, Kubernetes/legos/k8s_execute_local_script_on_a_pod/k8s_execute_local_script_on_a_pod.json, Kubernetes/legos/k8s_execute_local_script_on_a_pod/k8s_execute_local_script_on_a_pod.py
=> Action: Execute Local Script on a Pod

helm/Chart.yaml, helm/README.md, helm/templates/NOTES.txt, helm/templates/_helpers.tpl, helm/templates/deployment.yaml, helm/templates/service.yaml, helm/templates/serviceaccount.yaml, helm/templates/statefulset.yaml, helm/values.yaml
[EN-4630] 
This PR brings in support for statefulset to our Helm chart.
```
(base) [Awesome-CloudOps-Automation]- (EN-4630-jayasimha)$helm upgrade --install --namespace awesome-ops --create-namespace awesome-ops ./helm 
Release "awesome-ops" does not exist. Installing it now.
W0607 10:42:42.045118   20296 warnings.go:70] Autopilot increased resource requests for StatefulSet awesome-ops/awesome-ops-awesome-runbooks to meet requirements. See http://g.co/gke/autopilot-resources
NAME: awesome-ops
LAST DEPLOYED: Wed Jun  7 10:42:41 2023
NAMESPACE: awesome-ops …
```
=> En 4630 jayasimha

Opsgenie/legos/opsgenie_get_handle/README.md, Opsgenie/legos/opsgenie_get_handle/opsgenie_get_handle.json, Opsgenie/legos/opsgenie_get_handle/opsgenie_get_handle.py
[Issue-754](https://github.com/unskript/Awesome-CloudOps-Automation/issues/754)
=> Action: Get Opsgenie handle

AWS/legos/aws_filter_ebs_unattached_volumes/aws_filter_ebs_unattached_volumes.json, AWS/legos/aws_filter_instances_without_termination_and_lifetime_tag/aws_filter_instances_without_termination_and_lifetime_tag.json, AWS/legos/aws_filter_old_ebs_snapshots/aws_filter_old_ebs_snapshots.json, AWS/legos/aws_filter_public_s3_buckets_by_acl/aws_filter_public_s3_buckets_by_acl.json, AWS/legos/aws_filter_unencrypted_s3_buckets/aws_filter_unencrypted_s3_buckets.json, AWS/legos/aws_filter_unhealthy_instances_from_asg/aws_filter_unhealthy_instances_from_asg.json, AWS/legos/aws_filter_untagged_ec2_instances/aws_filter_untagged_ec2_instances.json, AWS/legos/aws_filter_unused_log_streams/aws_filter_unused_log_streams.json, AWS/legos/aws_filter_unused_nat_gateway/aws_filter_unused_nat_gateway.json, AWS/legos/aws_find_elbs_with_no_targets_or_instances/aws_find_elbs_with_no_targets_or_instances.json, AWS/legos/aws_find_idle_instances/aws_find_idle_instances.json, AWS/legos/aws_find_rds_instances_with_low_cpu_utilization/aws_find_rds_instances_with_low_cpu_utilization.json, AWS/legos/aws_find_redshift_cluster_without_pause_resume_enabled/aws_find_redshift_cluster_without_pause_resume_enabled.json, AWS/legos/aws_find_redshift_clusters_with_low_cpu_utilization/aws_find_redshift_clusters_with_low_cpu_utilization.json, AWS/legos/aws_find_s3_buckets_without_lifecycle_policies/aws_find_s3_buckets_without_lifecycle_policies.json, AWS/legos/aws_get_alb_listeners_without_http_redirect/aws_get_alb_listeners_without_http_redirect.json, AWS/legos/aws_get_ebs_volume_for_low_usage/aws_get_ebs_volume_for_low_usage.json, AWS/legos/aws_get_ebs_volumes_without_gp3_type/aws_get_ebs_volumes_without_gp3_type.json, AWS/legos/aws_get_older_generation_rds_instances/aws_get_older_generation_rds_instances.json, AWS/legos/aws_get_publicly_accessible_db_snapshots/aws_get_publicly_accessible_db_snapshots.json, AWS/legos/aws_get_stopped_instance_volumes/aws_get_stopped_instance_volumes.json, AWS/legos/aws_get_ttl_under_given_hours/aws_get_ttl_under_given_hours.json, AWS/legos/aws_get_unhealthy_instances_from_elb/aws_get_unhealthy_instances_from_elb.json, AWS/legos/aws_get_unused_route53_health_checks/aws_get_unused_route53_health_checks.json, AWS/legos/aws_list_clusters_with_low_utilization/aws_list_clusters_with_low_utilization.json, AWS/legos/aws_list_expiring_acm_certificates/aws_list_expiring_acm_certificates.json, AWS/legos/aws_list_unattached_elastic_ips/aws_list_unattached_elastic_ips.json, AWS/legos/aws_list_unhealthy_instances_in_target_group/aws_list_unhealthy_instances_in_target_group.json, AWS/legos/aws_list_unused_secrets/aws_list_unused_secrets.json
=> Update: Next hop mapping for Cost Opt legos

GCP/legos/gcp_describe_gke_cluster/gcp_describe_gke_cluster.py, GCP/legos/gcp_list_gke_cluster/gcp_list_gke_cluster.py
=> Amit fix gke describe cluster

AWS/AWS_Add_Lifecycle_Policy_To_S3_Buckets.ipynb, AWS/legos/aws_find_s3_buckets_without_lifecycle_policies/aws_find_s3_buckets_without_lifecycle_policies.py
[EN-4699](https://unskript.atlassian.net/browse/EN-4699)
[EN-4699]: https://unskript.atlassian.net/browse/EN-4699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update AWS S3 lifecycle policy check

Kubernetes/legos/k8s_get_cluster_health/k8s_get_cluster_health.py
Checks are not working correctly. Made a few fixes.
CPU and memory utilization checks are not correctly implemented. Taking them out for now.
We are only checking for status of pods, nodes and also if there are any warning present in the node logs.
=> Fix bugs in k8s cluster health check

.github/workflows/sanitize-runbook.yml, region_test.py, wrong_region.py
Ensures that no method signatures have any riffs of "region", but rather have "region" exactly, if at all.
=> Region test

helm/values.yaml
Resource requirement for the docker is more than 400Mi, increased it to 2Gi.
=> Make minimum RAM requirement to be 2GB

Kubernetes/K8S_Get_Candidate_Nodes_Given_Config.ipynb, Kubernetes/legos/k8s_get_candidate_nodes_for_pods/k8s_get_candidate_nodes_for_pods.py
Fix the candidate k8s lego as well as the runbook. Remove the aws specific stuff in there.
=> Amit fix candidate node lego generic

Kubernetes/K8S_Pod_Stuck_In_ImagePullBackOff_State.ipynb, sanitize.py
=> Fix sanitize to take care of credentialJson in code

AWS/AWS_Access_Key_Rotation.ipynb, AWS/AWS_Add_Lifecycle_Policy_To_S3_Buckets.ipynb, AWS/AWS_Add_Tag_Across_Selected_AWS_Resources.ipynb, AWS/AWS_Bulk_Update_Resource_Tag.ipynb, AWS/AWS_Delete_ELBs_With_No_Targets_Or_Instances.ipynb, AWS/AWS_Delete_IAM_User.ipynb, AWS/AWS_Delete_Redshift_Clusters_with_Low_CPU_Utilization.ipynb, AWS/AWS_Delete_Unused_AWS_Secrets.ipynb, AWS/AWS_Delete_Unused_Log_Streams.ipynb, AWS/AWS_Delete_Unused_NAT_Gateways.ipynb, AWS/AWS_Stop_Untagged_EC2_Instances.ipynb, AWS/AWS_Terminate_EC2_Instances_Without_Valid_Lifetime_Tag.ipynb, AWS/AWS_Update_Resource_Tags.ipynb, AWS/AWS_Update_Resources_About_To_Expire.ipynb, Kubernetes/Get_Kube_System_Config_Map.ipynb, Kubernetes/K8S_Delete_Pods_From_Failing_Jobs.ipynb, Kubernetes/K8S_Log_Healthcheck.ipynb, Kubernetes/K8S_Pod_Stuck_In_ImagePullBackOff_State.ipynb, Kubernetes/Resize_PVC.ipynb, Kubernetes/Rollback_k8s_Deployment_and_Update_Jira.ipynb, Kubernetes/legos/k8s_get_config_map_kube_system/k8s_get_config_map_kube_system.py
Fixes [EN-4937]
[EN-4937]: https://unskript.atlassian.net/browse/EN-4937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> - Fix default params in k8s runbooks

Kubernetes/K8S_Pod_Stuck_In_ImagePullBackOff_State_with_genai.ipynb
Add metadata to the cell, so that tooltip work required for [this](https://github.com/unskript/jlab-enhanced-cell-toolbar/pull/340) issue.
=> Add metadata info to work with tooltip on onboarding

Kubernetes/legos/k8s_check_worker_cpu_utilization/k8s_check_worker_cpu_utilization.py, Mongo/legos/mongodb_get_server_status/mongodb_get_server_status.py, SSH/legos/ssh_get_ec2_instances_with_low_available_disk_size/ssh_get_ec2_instances_with_low_available_disk_size.py, SSH/legos/ssh_get_ec2_instances_with_low_memory_size/ssh_get_ec2_instances_with_low_memory_size.py
=> Fix check legos

Mongo/legos/mongodb_get_server_status/README.md, Mongo/legos/mongodb_get_server_status/mongodb_get_server_status.py
=> fix default value

unskript-ctl/unskript-client.py
* Include SKIPPED cases too in the RESULTS
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/f3df137d-a91a-4af6-9eec-1c1ecbc24414
=> Include SKIPPED Result when showing results

build/templates/Makefile.extend-docker.template, unskript-ctl/templates/check.py.template, unskript-ctl/unskript-add-check.py
New script to create new check directory structure
```
base) amits-mbp-2:custom-checks amit$ python3 awesome/unskript-ctl/unskript-add-check.py -t AWS -n aws_list_ebs -d "List EBS volumes"
(base) amits-mbp-2:custom-checks amit$ cat actions/aws_
aws_get_ecs_services_status_v2/ aws_list_ebs/                   aws_list_unused_secrets/
(base) amits-mbp-2:custom-checks amit$ cat actions/aws_list_ebs/
__init__.py        aws_list_ebs.json  aws_list_ebs.py
(base) amits-mbp-2:custom-checks amit$ cat actions/aws_list_ebs/aws_list_ebs.*
{
"action_title": "aws_list_ebs",
"action_description": "List EBS volumes",
"action_type": "LEGO_TYPE_AWS",
"action_entry_function": "aws_list_ebs",
"action_needs_credential": true,
"action_output_type": "ACTION_OUTPUT_TYPE_LIST",
"action_is_check": true, …
```
=> Amit create new check script

README_extending_docker.md
Added Section on how to specify values for a variable used in check using the `unskript_config.yaml` file.
=> Updating section on how to assign values to variables used in checks

README_extending_docker.md
Reverts unskript/Awesome-CloudOps-Automation#881
=> Revert "Updating section on how to assign values to variables used in checks"

README_extending_docker.md
Read me update for adding custom check
=> REad me update for the custom check

Keycloak/legos/keycloak_get_audit_report/README.md, Keycloak/legos/keycloak_get_audit_report/keycloak_get_audit_report.json, Keycloak/legos/keycloak_get_audit_report/keycloak_get_audit_report.py, Keycloak/legos/keycloak_get_handle/README.md, Keycloak/legos/keycloak_get_handle/keycloak_get_handle.json, Keycloak/legos/keycloak_get_handle/keycloak_get_handle.py, Keycloak/legos/keycloak_get_service_health/README.md, Keycloak/legos/keycloak_get_service_health/keycloak_get_service_health.json, Keycloak/legos/keycloak_get_service_health/keycloak_get_service_health.py
1. Get Handle
2. Get Keycloak service status
3. Get Keycloak audit report
=> Keycloak legos

unskript-ctl/unskript-client.py
--report should be supported for all --rc options
```
(base) root@9d5b07d9c98c:~# unskript-ctl.sh -rc --check aws_get_ecs_services_without_autoscaling  --report
Executing Runbook -> /unskript/data/execution/workspace/c1929a6b-7425-4d9a-82ff-ef945142ffdd.ipynb
INFO:traitlets:Executing notebook with kernel: python3
╒═════════════════════════════════════════════╤══════════╤════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╕
│ Checks Name                                 │ Result   │   Failed Count │ Error                                                                                                                                    │ …
```
=> report support for all options

unskript-ctl/unskript_ctl.py
1. Change credential list to fetch details from unskript globals.
2. Group by Active at the top of the table.
3. Change indexing to start from 1 instead of 0.
=> Update list all credentials

unskript-ctl/unskript_ctl.py, unskript-ctl/unskript_ctl_gen_report.py
* Added support to send notification as email with attachment 
* Handled exceptions for boto3, sendgrid, smtp and slack notification. 
Here is the Testplan that has testcases used to validate the new feature. 
[testing_email_attachment.md](https://github.com/unskript/Awesome-CloudOps-Automation/files/13172350/testing_email_attachment.md)
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/2d4bd492-5291-4e38-bf65-38cb9fed7ecc
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/8e99c99f-03eb-47ca-989b-fda90be64ac1
=> Support email with attachments

unskript-ctl/unskript_ctl_config_parser.py
Since we need to support sending a combined report for checks/scripts run, make the ctl config parser handle that.
Incase, both check names and types are configured, then we will have 2 commands. The script option will be combined with types option.
All 3 present
```
jobs:
- name: trial # Unique name
notify: true
#notify_sink: foo
enable: true
checks:
- foo_bar
suites: []
connector_types:
- k8s
custom_scripts:
- ls -l
```
Cronjob
```
Programming crontab 0 0 * * * /usr/local/bin/unskript-ctl.sh -r --check --name foo_bar --report; /usr/local/bin/unskript-ctl.sh -r --check --type k8s --script "ls -l" --report
```
=> combine script and checks run

Kubernetes/legos/k8s_check_service_pvc_utilization/k8s_check_service_pvc_utilization.py, Kubernetes/legos/k8s_check_worker_cpu_utilization/k8s_check_worker_cpu_utilization.py, Kubernetes/legos/k8s_get_all_evicted_pods_from_namespace/k8s_get_all_evicted_pods_from_namespace.py, Kubernetes/legos/k8s_get_failed_deployments/k8s_get_failed_deployments.py, Kubernetes/legos/k8s_get_frequently_restarting_pods/k8s_get_frequently_restarting_pods.py, Kubernetes/legos/k8s_get_memory_utilization_of_services/k8s_get_memory_utilization_of_services.py, Kubernetes/legos/k8s_get_offline_nodes/k8s_get_offline_nodes.py, Kubernetes/legos/k8s_get_pending_pods/k8s_get_pending_pods.py, Kubernetes/legos/k8s_get_pods_in_imagepullbackoff_state/k8s_get_pods_in_imagepullbackoff_state.py, Kubernetes/legos/k8s_get_pods_in_not_running_state/k8s_get_pods_in_not_running_state.py, Kubernetes/legos/k8s_get_pods_with_high_restart/k8s_get_pods_with_high_restart.py
* Removed Import of ApiException imports 
=> Removing redundant imports

unskript-ctl/unskript_ctl_debug.py
Added more debug when the remote session doesnt come up.
Bad case
```
(base) root@awesome-awesome-runbooks-0:~# unskript-ctl.sh --debug --start --config $PWD/client-abc.ovpn
Error Occured while starting the Debug Session. Here are the logs from openvpn
===============================================================================================
Thu Dec 14 19:09:22 2023 Unrecognized option or missing or extra parameter(s) in /home/jovyan/client-abc.ovpn:18: block-outside-dns (2.4.7)
Thu Dec 14 19:09:22 2023 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar 22 2022
Thu Dec 14 19:09:22 2023 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Thu Dec 14 19:09:22 2023 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' …
```
=> More error logging for debug session

unskript-ctl/unskript_ctl_factory.py, unskript-ctl/unskript_ctl_notification.py
* Incorporated reading config file via EnvYAML
* Fixed logic of report generation for script, script+check and only check runs. 
* 
=> Notification Fix

unskript-ctl/unskript_ctl_database.py, unskript-ctl/unskript_ctl_factory.py, unskript-ctl/unskript_ctl_main.py, unskript-ctl/unskript_ctl_notification.py, unskript-ctl/unskript_ctl_run.py
[EN-5240]
* Incorported Custom Logger that has intelligence to dump logs that are debug and above to a file
* Only INFO logs are printed to console. 
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/ea845e4a-67fe-4c62-a666-b2287df3f153
[EN-5240]: https://unskript.atlassian.net/browse/EN-5240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Incorporated Custom Logger

Kafka/legos/kafka_get_topics_with_lag/kafka_get_topics_with_lag.py, unskript-ctl/unskript_ctl_config_parser.py
Lag should be calculated in a sliding window, rather than exact value.
For now, we take 2 sample sets at 30 sec apart and then compare the difference between the lags. If its more than the threshold, we consider it failed.
```
root@awesome-awesome-runbooks-0:/# unskript-ctl.sh run check --type kafka
Running: 100%|████████████████████████████████████████████████████████| 7/7 [01:00<00:00,  8.62s/it]
╒══════════════════════════════════╤══════════╤════════════════╤═══════════════════════╕
│ Checks Name                      │ Result   │   Failed Count │ Error                 │
╞══════════════════════════════════╪══════════╪════════════════╪═══════════════════════╡
│ Kafka Check Offline Partitions   │  ERROR   │              0 │ 'Connection time-out' │ …
```
=> Bring sliding window for kafka lag

ElasticSearch/legos/elasticsearch_get_cluster_statistics/elasticsearch_get_cluster_statistics.json, Kafka/legos/kafka_get_committed_messages_count/kafka_get_committed_messages_count.json, Kafka/legos/kafka_get_topic_health/kafka_get_topic_health.json, Keycloak/legos/keycloak_get_audit_report/keycloak_get_audit_report.json, Kubernetes/legos/k8s_get_all_resources_utilization_info/k8s_get_all_resources_utilization_info.json, Kubernetes/legos/k8s_get_node_status_and_resource_utilization/k8s_get_node_status_and_resource_utilization.json, Kubernetes/legos/k8s_get_nodes_pressure/k8s_get_nodes_pressure.json, Kubernetes/legos/k8s_get_service_images/k8s_get_service_images.json, Kubernetes/legos/k8s_get_versioning_info/k8s_get_versioning_info.json, Kubernetes/legos/k8s_measure_worker_node_network_bandwidth/k8s_measure_worker_node_network_bandwidth.json, Mongo/legos/mongodb_get_metrics/mongodb_get_metrics.json, Mongo/legos/mongodb_get_replica_set/mongodb_get_replica_set.json, Mongo/legos/mongodb_get_write_conflicts/mongodb_get_write_conflicts.json, Redis/legos/redis_get_keys_count/redis_get_keys_count.json, Redis/legos/redis_get_metrics/redis_get_metrics.json
[EN-5257](https://unskript.atlassian.net/browse/EN-5257)
[EN-5257]: https://unskript.atlassian.net/browse/EN-5257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update CATEGORY_TYPE_INFORMATION for lb legos

unskript-ctl/unskript_ctl_database.py, unskript-ctl/unskript_ctl_main.py, unskript-ctl/unskript_ctl_run.py, unskript-ctl/unskript_ctl_version.py
* Adding Schema Version to the PSS DB
```
def is_schema_version_present(db_path):
db = DB(db_path)
with db.transaction() as connection:
root = connection.root()
print(f"ALL KEYS: {root.keys()}")
data = root.get('schema_version')
if data is None:    
return False 
del root
del connection 
return True 
OUTPUT: ALL KEYS: KeysView({'audit_trail': {}, 'schema_version': '1.0.0'})
```
=> Adding schema version to the PSS DB

Kubernetes/legos/k8s_get_nodes_with_insufficient_resources/k8s_get_nodes_with_insufficient_resources.py, unskript-ctl/unskript_ctl_main.py, unskript-ctl/unskript_ctl_run.py
matrix support was regressed as part of removing ipynb file.
One issue different from ipynb file is eval on named variables was not working, so for task line, we end putting up the actual value, rather than variable name
=> Fix matrix regression

ElasticSearch/legos/elasticsearch_check_large_index_size/elasticsearch_check_large_index_size.py, Mongo/legos/mongodb_check_large_index_size/mongodb_check_large_index_size.py, Mongo/legos/mongodb_compare_disk_size_to_threshold/mongodb_compare_disk_size_to_threshold.py, Mongo/legos/mongodb_get_server_status/mongodb_get_server_status.py, Postgresql/legos/postgresql_get_server_status/postgresql_get_server_status.py, Redis/legos/redis_get_cluster_health/redis_get_cluster_health.py, Redis/legos/redis_list_large_keys/redis_list_large_keys.py
As suggested by lightbeam [here](https://docs.google.com/spreadsheets/d/1AeKc0GmLPiI5tVJUkOG97omLyGMnxxTAcD_mDbnSyVI/edit#gid=1646865108)
=> Change default values for checks

unskript-ctl/unskript_ctl_main.py
Move session upload from start session to stop session
=> Move session logs upload to stop session

ElasticSearch/legos/elasticsearch_check_health_status/elasticsearch_check_health_status.py, Kubernetes/legos/k8s_check_cronjob_pod_status/k8s_check_cronjob_pod_status.py, Kubernetes/legos/k8s_check_service_pvc_utilization/k8s_check_service_pvc_utilization.py, Kubernetes/legos/k8s_check_service_status/k8s_check_service_status.py, Kubernetes/legos/k8s_get_cluster_health/k8s_get_cluster_health.py, Kubernetes/legos/k8s_get_expiring_certificates/k8s_get_expiring_certificates.py, Kubernetes/legos/k8s_get_memory_utilization_of_services/k8s_get_memory_utilization_of_services.py, Kubernetes/legos/k8s_get_pods_in_not_running_state/k8s_get_pods_in_not_running_state.json, Kubernetes/legos/k8s_get_pods_in_not_running_state/k8s_get_pods_in_not_running_state.py, Postgresql/legos/postgresql_check_unused_indexes/postgresql_check_unused_indexes.py
=> Lb checks fix logic

.github/workflows/build-and-release-docker-lite.yml, .github/workflows/build-and-release-docker.yml
* Added docker scout to the Docker and Docker lite builds
* Added logic to delete the image if docker scout flags Critical error, from docker hub.
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/d28c0ff7-e99d-4c0b-b9e2-93fd080798b4
=> Add CVE checks

Keycloak/legos/keycloak_get_service_health/keycloak_get_service_health.json
=> disable keycloak check

Keycloak/legos/keycloak_get_audit_report/keycloak_get_audit_report.py, Keycloak/legos/keycloak_get_service_health/keycloak_get_service_health.json, Keycloak/legos/keycloak_get_service_health/keycloak_get_service_health.py
* Implemented REST based API calls for keycloak Actions.
```
root@awesome-awesome-runbooks-0:~/test# python ./keycloak_get_service_health.py
Keycloak Service is Healthy. Master realm is available.
root@awesome-awesome-runbooks-0:~/test# 
```
```
root@awesome-awesome-runbooks-0:~/test# python ./keycloak_get_audit_report.py
+---------------------+--------+--------------------------------------+-------------+----------------+---------+
| Time                | Type   | User ID                              | Client ID   | IP Address     | Error   | …
```
=> Implementing REST wrapper for keycloak legos

Keycloak/legos/keycloak_get_audit_report/keycloak_get_audit_report.py, Keycloak/legos/keycloak_get_service_health/keycloak_get_service_health.py, unskript-ctl/unskript_ctl_database.py, unskript-ctl/unskript_utils.py
* Fixed issue with Keycloak check which complained about bear type
* List info --all for not displaying all info legos 
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/3facd4ed-c689-4dcb-871f-201e9d9d39b9
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/4641f1bb-8157-4477-b558-e8a15737ca2d
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/30348c55-17c4-4000-ab05-2d076d21b0bf
=> Fixes for Keycloak legos not working

.github/workflows/build-and-release-docker-lite.yml
Fix: [EN-5280](https://unskript.atlassian.net/browse/EN-5280)
Build docker image wit custom gotty
https://github.com/unskript/Awesome-CloudOps-Automation/actions/runs/7847722758
[EN-5280]: https://unskript.atlassian.net/browse/EN-5280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EN-5280: Build docker with custom gotty

unskript-ctl/config/unskript_ctl_config.yaml, unskript-ctl/templates/template_script.j2, unskript-ctl/unskript_ctl_factory.py, unskript-ctl/unskript_ctl_main.py, unskript-ctl/unskript_ctl_notification.py, unskript-ctl/unskript_ctl_run.py, unskript-ctl/unskript_utils.py
Priority for checks, so that the report can show per priority report, with FAIL, ERROR in the top followed by PASS
**status_list_of_dict** was changed to have per priority, per status - list of checks, instead of being a flat list.
TODO: 
1. **check_names**, **check_entry_function**,  **check_uuids** should be combined into a class, instead of individual field.
2. We should have proper classes instead of dicts with no schema, its hard to maintain. like status_list_of_dict, for eg. There are so many fields like this without schema.
3. Slack message can have per priority notifications as well
Slack notification
=> support for priority for checks

Kubernetes/legos/k8s_get_memory_utilization_of_services/k8s_get_memory_utilization_of_services.py, unskript-ctl/unskript_ctl_database.py
Reverts unskript/Awesome-CloudOps-Automation#989
Backing out this fix after reviewing it with @abhishek-unskript
=> Revert "Fix: update method in unskript_ctl_db"

Kafka/legos/kafka_get_topics_with_lag/kafka_get_topics_with_lag.py, Kubernetes/legos/k8s_get_cluster_health/k8s_get_cluster_health.py, Kubernetes/legos/k8s_get_expiring_certificates/k8s_get_expiring_certificates.py, Kubernetes/legos/k8s_get_frequently_restarting_pods/k8s_get_frequently_restarting_pods.json, Kubernetes/legos/k8s_get_memory_utilization_of_services/k8s_get_memory_utilization_of_services.py, Kubernetes/legos/k8s_get_pending_pods/k8s_get_pending_pods.json
[EN-5297](https://unskript.atlassian.net/browse/EN-5297)
- K8s get cluster health with core services
- K8s get cluster health without core services
[EN-5297]: https://unskript.atlassian.net/browse/EN-5297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revise logic for checks and remove redundant checks

Kafka/legos/kafka_get_committed_messages_count/kafka_get_committed_messages_count.py, Kafka/legos/kafka_get_topic_health/kafka_get_topic_health.py, Kubernetes/legos/k8s_get_nodes_pressure/k8s_get_nodes_pressure.json, Kubernetes/legos/k8s_get_nodes_pressure/k8s_get_nodes_pressure.py, Kubernetes/legos/k8s_measure_worker_node_network_bandwidth/k8s_measure_worker_node_network_bandwidth.py, Mongo/legos/mongodb_get_metrics/mongodb_get_metrics.py, Redis/legos/redis_get_keys_count/redis_get_keys_count.py
- Info legos
```
root@awesome-awesome-runbooks-0:~# unskript-ctl.sh run --info
Information Gathering Action Results
Running: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:20<00:00,  5.07s/it]
redis/redis_get_keys_count
{'Matched keys count': 3}
###
mongodb/mongodb_get_metrics
Total Memory: 488 MB
Database    Collection                         Index Size (KB)    Storage Size (KB)
----------  -------------------------------  -----------------  -------------------
admin       system.version                                  20                   20
admin       system.keys                                     36 …
```
=> Revise Info legos

Kafka/legos/kafka_get_committed_messages_count/kafka_get_committed_messages_count.py, unskript-ctl/unskript_ctl_notification.py
=> Update kafka get committed messages info lego

Kubernetes/legos/k8s_check_service_pvc_utilization/k8s_check_service_pvc_utilization.py, Kubernetes/legos/k8s_get_memory_utilization_of_services/k8s_get_memory_utilization_of_services.py, Kubernetes/legos/k8s_get_pending_pods/k8s_get_pending_pods.json
Details attached in [EN-5332](https://unskript.atlassian.net/browse/EN-5332)
[EN-5332]: https://unskript.atlassian.net/browse/EN-5332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Calculate per container service memory utilization

.github/workflows/build-and-release-docker-lite.yml, unskript-ctl/unskript_ctl_notification.py, unskript-ctl/unskript_ctl_run.py
This PR brings in the following
* The Docker Build is streamlined to build only `x86-64` and not `aarch64`
* The Docker biuld time is reduced from 2+ hours to 25 minutes. 
* The introduction of non-root user `unskript` also needs some changes to unskript-ctl. This PR brings in that changes too
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/621902da-4e20-4d27-a389-9e8c4e562376
https://github.com/unskript/Awesome-CloudOps-Automation/assets/87547684/ed483d40-292e-44a4-875a-a5afd3dfe71f
```
unskript@awesome-awesome-runbooks-0:~$ …
```
=> Add support to run docker in non-root user mode

unskript-ctl/unskript_ctl_notification.py
=> Changes to notification.py

Mongo/legos/mongodb_get_server_status/README.md, Mongo/legos/mongodb_get_server_status/mongodb_get_server_status.json, Mongo/legos/mongodb_get_server_status/mongodb_get_server_status.py
[EN-5402](https://unskript.atlassian.net/browse/EN-5402)
[EN-5402]: https://unskript.atlassian.net/browse/EN-5402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Mongodb server status check

Kubernetes/legos/k8s_get_pending_pods/k8s_get_pending_pods.py, Kubernetes/legos/k8s_get_pods_in_crashloopbackoff_state/k8s_get_pods_in_crashloopbackoff_state.py
[EN-5535](https://unskript.atlassian.net/browse/EN-5535)
1. Crashloopback pods
3. Pending pods
[EN-5535]: https://unskript.atlassian.net/browse/EN-5535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update checks: Crashloopback and Pending pods for time based interval check

Kubernetes/legos/k8s_get_oomkilled_pods/k8s_get_oomkilled_pods.py, Kubernetes/legos/k8s_get_pods_in_crashloopbackoff_state/k8s_get_pods_in_crashloopbackoff_state.py
[EN-5547](https://unskript.atlassian.net/browse/EN-5547)
1. OOMKilled pods
2. Crashloopback pods
[EN-5547]: https://unskript.atlassian.net/browse/EN-5547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update check to consider number of restarts

.github/workflows/all_module_test.yml, unskript-ctl/unskript_ctl_run.py, unskript-ctl/unskript_upload_results_to_s3.py
[EN-5574](https://unskript.atlassian.net/browse/EN-5574)
[EN-5574]: https://unskript.atlassian.net/browse/EN-5574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add check output JSON to tarball

Kubernetes/legos/k8s_get_oomkilled_pods/k8s_get_oomkilled_pods.py, Kubernetes/legos/k8s_get_pods_in_crashloopbackoff_state/k8s_get_pods_in_crashloopbackoff_state.py
Reverts unskript/Awesome-CloudOps-Automation#1069
=> Revert "Update check to consider number of restarts"

unskript-ctl/unskript_ctl_main.py, unskript-ctl/unskript_ctl_run.py, unskript-ctl/unskript_ctl_upload_session_logs.py
Fixes [EN-5749]
This PR brings in support for
*  running On-Demand Script that are kept at `/unskript/ondemand` folder.
* Skipping diagnostics by setting `SKIP_DEBUGS` environment variable
```
unskript@awesome-awesome-runbooks-0:~$ unskript-ctl.sh run check --type vault
Running: 100%|████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.22it/s]
╒══════════════════════════╤══════════╤════════════════╤═════════╕
│ Checks Name              │ Result   │   Failed Count │ Error   │
╞══════════════════════════╪══════════╪════════════════╪═════════╡
│ Get Vault service health │  PASS    │              0 …
```
=> [EN-5749]: Adding on-demand script run support

.github/workflows/all_module_test.yml, Kubernetes/legos/k8s_check_service_pvc_utilization/k8s_check_service_pvc_utilization.py
* Refactoring PVC Utilization calculation
=> Pvc utilization refactor

unskript-ctl/unskript_audit_cleanup.py
* Improved logic of deleting the Old execution directories that are greater than the Audit period.
* Removed function that was deleting just the ipynb files, replaced with shutil.rmtree instead
=> Changed Logic to remove old execution directories instead of just ipyb files
